// Ještě další karty dávných dob – dvanáct nových situací pro každou dobu 1–6, aby se karty méně opakovaly.
// Postavy z AGE_PEOPLE příslušné doby. Několik karet má pokračování (`next` + `in`, karta s `queueOnly`).

const o = ([t, e, more = {}]) => ({ t, e, ...more });
const c = (id, age, who, text, l, r, u, d, extra = {}) => ({ id, age, who, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) }, ...extra });
const Q = { queueOnly: true };

export const AGE_CARDS_EXTRA = [
  // ── Pravěk ────────────────────────────────────────────
  c('x1_vor', 1, 'lov', 'Svázala jsem kmeny liánami a přeplula řeku, {osl}! Na druhém břehu se pasou stáda, která ještě nikdo nelovil. Chci tam vzít další lovce.',
    ['Plout všichni', { fin: 10, lid: -5, sil: -5 }], ['Řeka je zrádná', { lid: 5, fin: -5 }], ['Postavit víc vorů', { ved: 10, pri: -5, fin: -5 }], ['Jen ty a dva lovci', { sil: 5, fin: 5, lid: -5 }, { rel: { lov: 1 } }]),
  c('x1_sul', 1, 'sber', 'Za bažinou je bílá skála, kterou zvířata olizují. Je slaná! Maso se solí nezkazí ani v létě. Sousedé o ní ale vědí taky.',
    ['Hlídat skálu', { sil: 5, fin: 5, dip: -10 }], ['Dělit se se sousedy', { dip: 10, fin: -5 }], ['Lovit zvěř u skály', { fin: 10, pri: -10 }], ['Měnit sůl za pazourky', { fin: 5, dip: 5, sil: -5 }]),
  c('x1_dvojcata', 1, 'sam', 'Lusa porodila dvojčata. Šaman tvrdí, že dvě děti naráz jsou zlé znamení a matka s nimi musí odejít z tábora.',
    ['Nikdo neodejde', { lid: 10, vir: -10 }], ['Poslechnout šamana', { vir: 10, lid: -15 }], ['Obřad očisty', { vir: 5, fin: -10, lid: 5 }], ['Ať žijí na kraji tábora', { vir: 5, lid: -5, sil: -5 }]),
  c('x1_jehla', 1, 'sber', 'Vybrousila jsem z kosti tenkou jehlu s ouškem. Kožešiny se dají sešít těsně k tělu – nikdo nebude mrznout. Jen šití zabere celé dny.',
    ['Všichni šít', { lid: 10, fin: -10 }], ['Šít jen pro děti', { lid: 5, ved: 5, sil: -5 }], ['Naučit i lovce', { ved: 10, sil: -5 }], ['Na to nemáme čas', { fin: 5, ved: -5, lid: -5 }]),
  c('x1_kvaseni', 1, 'sber', 'Plody v duté kládě zkvasily. Kdo se napil té šťávy, smál se a zpíval celou noc. Ráno ale dva lovci nevstali na lov.',
    ['Slavnost pro všechny', { lid: 10, sil: -10 }], ['Šťávu vylít', { sil: 5, lid: -10 }], ['Jen pro obřady', { vir: 10, lid: -5 }], ['Zkoumat, jak to vzniká', { ved: 5, fin: -5, vir: -5 }]),
  c('x1_zeme', 1, 'star', 'V noci se zachvěla země. Ve stropě naší jeskyně je nová puklina a padá z ní kamení. Starší se bojí vejít dovnitř, {osl}.',
    ['Odejít hned', { lid: 5, fin: -10 }], ['Podepřít strop kmeny', { ved: 5, pri: -10, sil: 5 }], ['Uprosit duchy hor', { vir: 10, lid: -5 }], ['Spát venku u ohně', { pri: 5, lid: -5, sil: -5 }]),
  c('x1_ztraceny', 1, 'lov', 'V mlze se ztratil malý chlapec, {osl}. Les je plný vlků a za chvíli bude tma. Mám vést lovce na hledání?',
    ['Hledat všichni', { lid: 10, sil: -10 }], ['Počkat do rána', { sil: 5, lid: -10 }], ['Zapálit ohně na kopcích', { lid: 5, pri: -10, ved: 5 }], ['Šaman ať prosí duchy', { vir: 5, lid: -5 }]),
  c('x1_kone', 1, 'lov', 'Na pláni se pase stádo divokých koní. Lovci je chtějí zahnat do rokle. Jedna dívka ale tvrdí, že hříbě jí už žere z ruky.',
    ['Zahnat stádo do rokle', { fin: 15, pri: -10, lid: -5 }], ['Ochočit hříbě', { ved: 10, fin: -5 }], ['Ulovit jen staré', { fin: 5, sil: -5 }], ['Koně jsou duchové větru', { vir: 5, pri: 5, fin: -10 }]),
  c('x1_pribehy', 1, 'star', 'Jsem starý, {osl}. Chci, aby se mladí naučili zpaměti příběhy předků, než umřu. Jenže to znamená, že nepůjdou na lov.',
    ['Ať se učí', { vir: 5, ved: 5, fin: -10 }], ['Lov je důležitější', { fin: 5, vir: -10 }], ['Vyprávět u ohně večer', { lid: 5, vir: 5, sil: -5 }], ['Namalovat je na skálu', { ved: 10, lid: -5 }, { rel: { star: 1 } }]),
  c('x1_hory', 1, 'ciz', 'Za horami je hora, která kouří. Pod ní leží černý kámen ostřejší než pazourek. Zavedu tam tvé lidi – za tři kožešiny.',
    ['Poslat výpravu', { ved: 5, fin: -5, lid: -5 }, { next: 'x1_hory2', in: 3 }], ['Nevěřit mu', { dip: -10, sil: 5 }], ['Ať přinese kámen sám', { fin: -10, dip: 5 }], ['Jít sám s ním', { vir: 5, dip: 5, sil: -10 }]),
  c('x1_hory2', 1, 'ciz', 'Výprava se vrátila s vaky černého skla! Jeden lovec ale zůstal v horách – oženil se s dívkou z mého kmene. Moji lidé teď chtějí víc kožešin.',
    ['Dát jim kožešiny', { dip: 10, fin: -10 }], ['Přivést lovce zpátky', { sil: 5, dip: -10 }], ['Slavit spojenectví', { dip: 5, lid: 5, vir: -5 }], ['Vyrobit čepele na výměnu', { fin: 10, ved: 5, pri: -5, lid: -5 }], Q),
  c('x1_tetovani', 1, 'sam', 'Mladí chtějí po prvním lovu znamení na kůži – sazemi a trnem. Šaman říká, že bez něj je duchové nepoznají. Matky se bojí, že se rány zanítí.',
    ['Znamení pro každého', { vir: 10, lid: -5 }], ['Jen barvou, ne trnem', { lid: 5, vir: -5 }], ['Až po těžké zkoušce', { sil: 5, vir: 5, lid: -10 }], ['Zakázat to', { ved: 5, vir: -10 }]),
  c('x1_kanci', 1, 'sber', 'Divočáci v noci rozryli celou louku s kořínky, které jsme sbíraly na zimu. Bez nich budeme mít hlad, {osl}.',
    ['Uspořádat hon', { fin: 10, sil: -5, pri: -5 }], ['Kolem louky plot', { ved: 5, fin: -5, lid: -5 }], ['Hledat nové louky', { pri: 5, lid: -5, dip: -5 }], ['Duchové nás trestají', { vir: 5, fin: -10 }]),

  // ── Starověk ──────────────────────────────────────────
  c('x2_lom', 2, 'voj', 'Otroci v kamenolomu odhodili nástroje a odmítají pracovat. Říkají, že je dozorci bijí a nedávají jim vodu. Mám tam vyrazit, {osl}?',
    ['Potlačit vzpouru', { sil: 5, lid: -10 }], ['Vyměnit dozorce', { lid: 10, fin: -5 }], ['Slíbit svobodu po letech', { lid: 5, fin: -10, sil: 5 }], ['Lom zavřít', { pri: 5, fin: -10 }]),
  c('x2_akvadukt', 2, 'pis', 'Město žízní, {osl}. Z hor bychom mohli přivést vodu po kamenných obloucích přes celé údolí. Spočítal jsem to – stavba spolkne deset let.',
    ['Stavět akvadukt', { lid: 10, fin: -15 }], ['Kopat studny', { fin: -5, ved: -5, lid: 5 }], ['Ať to platí boháči', { fin: 5, lid: 5, dip: -10 }], ['Voda jen pro palác', { fin: 5, lid: -10 }]),
  c('x2_purpura', 2, 'kup', 'Z mořských plžů umím vyrobit purpur – barvu, za kterou cizí králové platí zlatem. Jen se přitom hrozně páchne v celém přístavu.',
    ['Barvírny u přístavu', { fin: 15, pri: -10, lid: -5 }], ['Daleko za městem', { fin: 5, pri: -5 }], ['Purpur jen pro krále', { vir: 5, sil: 5, fin: -10 }], ['Prodat tajemství', { dip: 10, fin: 5, ved: -10 }]),
  c('x2_hrobka', 2, 'knez', 'Chytili jsme lupiče v hrobce tvého děda, {osl}! Ukradli zlatou masku. Prý je najal někdo z paláce.',
    ['Veřejná poprava', { vir: 10, lid: -10 }], ['Vyslechnout je', { sil: 5, ved: 5, vir: -5 }], ['Hrobky hlídat vojskem', { vir: 5, fin: -10 }], ['Masku roztavit na zlato', { fin: 10, vir: -15 }]),
  c('x2_divadlo', 2, 'filo', 'Básník napsal komedii, ve které vystupuje hloupý král s oslíma ušima. Celé město se směje – a všichni vědí, o koho jde.',
    ['Smát se s nimi', { lid: 10, sil: -5 }], ['Hru zakázat', { sil: 5, lid: -10, ved: -5 }], ['Odpovědět vlastní hrou', { lid: 5, ved: 5, fin: -5 }], ['Básníka vyhnat', { vir: 5, dip: -5, lid: -5 }]),
  c('x2_vozy', 2, 'voj', 'Sousedé mají válečné vozy s lehkými koly a koňmi. Projedou naší pěchotou jako nůž máslem. Potřebuju vozy taky, {osl}.',
    ['Stovky vozů', { sil: 15, fin: -15 }], ['Kopí proti koním', { sil: 5, ved: 5, fin: -5 }], ['Koupit koně od nomádů', { dip: 10, fin: -10 }], ['Mír se sousedy', { dip: 10, sil: -10 }]),
  c('x2_rukojmi', 2, 'voj', 'Sousední král nám posílá svého syna, aby vyrůstal u tvého dvora jako záruka míru. Chce ale, abychom mu poslali někoho z tvé rodiny.',
    ['Vyměnit děti', { dip: 15, lid: -5, sil: -5 }], ['Přijmout jen jeho', { sil: 5, dip: -5, fin: 5 }], ['Vychovat ho jako našeho', { dip: 5, ved: 5, fin: -5 }], ['Odmítnout', { dip: -10, sil: 5 }]),
  c('x2_lekar', 2, 'filo', 'Lékař chce otevírat těla mrtvých, aby pochopil, jak funguje srdce. Kněží říkají, že duše zemřelých pak nenajdou cestu do podsvětí.',
    ['Dovolit mu to', { ved: 15, vir: -10 }], ['Jen těla zločinců', { ved: 5, vir: -5, sil: 5 }], ['Ať zkoumá zvířata', { ved: 5, pri: -5 }], ['Zakázat to', { vir: 10, ved: -10 }]),
  c('x2_majak', 2, 'kup', 'Lodě se tříští o útesy před přístavem. Postavme na ostrově maják s ohněm na vrcholu – bude ho vidět půl dne plavby!',
    ['Postavit maják', { fin: -10, dip: 10, ved: 5 }], ['Lodě ať platí lodivoda', { fin: 10, dip: -5, lid: -5 }], ['Maják i s chrámem', { vir: 5, fin: -10, dip: 5 }], ['Útesy chrání město', { sil: 5, dip: -10 }]),
  c('x2_dluhy', 2, 'pis', 'Polovina rolníků je zadlužená a prodávají sebe i děti do otroctví, aby splatili věřitele. Brzy nebude kdo obdělávat pole, {osl}.',
    ['Zrušit všechny dluhy', { lid: 15, fin: -10, dip: -5 }], ['Zakázat otroctví za dluh', { lid: 10, fin: -5, sil: -5 }], ['Dluh je dluh', { fin: 10, lid: -15 }], ['Půjčky z chrámu', { vir: 5, lid: 5, fin: -10 }]),
  c('x2_pozar', 2, 'voj', 'V hrnčířské čtvrti vypukl požár a vítr ho žene k sýpkám! Můžu strhnout domy v cestě ohně, ale lidé tam ještě mají majetek.',
    ['Strhnout domy', { fin: 5, lid: -10 }], ['Hasit vodou z řeky', { lid: 5, fin: -10 }], ['Zachránit sýpky', { fin: 10, lid: -5, sil: -5 }], ['Modlit se za déšť', { vir: 5, fin: -10, lid: -5 }]),
  c('x2_sen', 2, 'knez', 'Zdálo se ti o sedmi tučných a sedmi hubených kravách, {osl}. Velekněz to vykládá jako sedm let hojnosti a sedm let hladu.',
    ['Plnit sýpky', { fin: -10, lid: -5, vir: 5 }, { next: 'x2_sen2', in: 5 }], ['Je to jen sen', { fin: 5, vir: -10 }], ['Oběti, ať hlad nepřijde', { vir: 10, fin: -10 }], ['Zeptat se písařů', { ved: 5, vir: -5 }]),
  c('x2_sen2', 2, 'knez', 'Sen se splnil – řeka letos nezaplavila pole a všude je hlad. Jen naše sýpky jsou plné. U bran stojí hladoví lidé ze sousedních zemí.',
    ['Dát jim obilí zdarma', { dip: 15, fin: -10 }], ['Prodat ho za zlato', { fin: 15, dip: -10 }], ['Nejdřív naši lidé', { lid: 10, dip: -10 }], ['Obilí za půdu', { fin: 5, sil: 5, dip: -5, lid: -5 }], Q),

  // ── Středověk ─────────────────────────────────────────
  c('x3_mlyn', 3, 'sedl', 'Pán postavil na potoce mlýn a teď nám zakazuje mlít obilí doma na žernovech. Za každý pytel chce desetinu mouky, {osl}.',
    ['Mlýn je pro všechny', { lid: 10, fin: -5, sil: -5 }], ['Pán má pravdu', { fin: 10, lid: -10 }], ['Snížit poplatek', { lid: 5, fin: -5 }], ['Druhý mlýn pro obec', { lid: 5, pri: -5, fin: -5 }]),
  c('x3_hrad', 3, 'ryt', 'Náš dřevěný hrádek by neodolal ani pořádné bouřce, natož nepříteli. Postavme na skále kamenný hrad s věží, {osl}.',
    ['Kamenný hrad', { sil: 15, fin: -15 }], ['Opravit palisádu', { sil: 5, fin: -5, pri: -5 }], ['Hrad postaví robotníci', { sil: 10, lid: -10 }], ['Raději opevnit město', { lid: 5, sil: 5, fin: -10 }]),
  c('x3_cech', 3, 'sedl', 'Můj syn je šikovný kovář, ale městský cech mu nedovolí prodávat na trhu. Prý nemá mistrovský list a není z města.',
    ['Cechy mají pravdu', { fin: 5, lid: -10 }], ['Trh pro každého', { lid: 10, fin: -5, dip: -5 }], ['Ať se vyučí u mistra', { ved: 5, lid: -5 }], ['Venkovský trh', { lid: 5, fin: 5, sil: -5 }]),
  c('x3_relikvie', 3, 'bisk', 'Potulný mnich nabízí kost svatého Víta. Kdyby byla v našem kostele, přicházely by tisíce poutníků. Chce za ni ale celý stříbrný poklad.',
    ['Koupit relikvii', { vir: 15, fin: -10 }], ['Je to podvodník', { ved: 5, vir: -5 }], ['Smlouvat o cenu', { fin: -5, vir: 5, dip: -5 }], ['Dát ho zavřít', { sil: 5, vir: -5, lid: -5 }]),
  c('x3_loupeznici', 3, 'ryt', 'Na kupecké stezce přepadají vozy loupeživí rytíři, {osl}. Jejich vůdce je můj bratranec. Prosím, nechte mě s ním nejdřív promluvit.',
    ['Ať promluví', { dip: 5, fin: -5 }, { rel: { ryt: 1 } }], ['Hrad dobýt', { sil: -10, fin: 10, lid: 5 }], ['Dát jim službu u dvora', { sil: 10, lid: -10 }], ['Kupci ať platí stráž', { fin: 5, dip: -10 }]),
  c('x3_kolonisti', 3, 'sedl', 'Za horami žijí osadníci, kteří by přišli vymýtit pohraniční hvozdy a založit vsi. Chtějí vlastní právo a deset let bez daní.',
    ['Pozvat je', { fin: 10, pri: -10, lid: -5 }], ['Půda pro naše sedláky', { lid: 10, fin: -5, pri: -5 }], ['Pozvat, ale s daní', { fin: 5, dip: -5, lid: -5 }], ['Hvozdy nechat být', { pri: 10, fin: -10 }]),
  c('x3_kronika', 3, 'bisk', 'Mnich Kosmas píše kroniku a ptá se, jak má popsat tvou vládu. Chce prý psát pravdu, ale pravda se dá napsat různě, {osl}.',
    ['Ať píše pravdu', { ved: 10, vir: -5, sil: -5 }], ['Ať mě oslavuje', { sil: 5, ved: -10 }], ['Zaplatit mu', { vir: 5, fin: -10 }], ['Psát o lidu, ne o mně', { lid: 10, ved: 5, sil: -10 }]),
  c('x3_stribro', 3, 'alch', 'Havíři u lesního potoka našli stříbrnou žílu, {osl}! Ze všech koutů se sem hrnou zlatokopové a kopou, kde se dá.',
    ['Kopat ve velkém', { fin: 15, pri: -15 }, { next: 'x3_stribro2', in: 4 }], ['Doly pod dohledem', { fin: 5, sil: 5, pri: -5 }], ['Zabrat vše pro korunu', { fin: 10, lid: -10 }], ['Les je posvátný', { vir: 5, pri: 5, fin: -10 }]),
  c('x3_stribro2', 3, 'alch', 'Z dolů teče stříbro proudem, ale každý razí vlastní mince a nikdo neví, co platí. Havíři navíc stávkují kvůli zatopeným štolám.',
    ['Jedna mince pro zemi', { fin: 10, dip: 5, lid: -5 }], ['Pumpy do štol', { ved: 10, fin: -10 }], ['Havíře potrestat', { sil: 5, lid: -15 }], ['Podíl pro havíře', { lid: 10, fin: -10 }], Q),
  c('x3_masopust', 3, 'sedl', 'O masopustu lidé chodí v maskách a jeden se převlékl za biskupa na koze. Biskup Vojtěch žádá, abys masky zakázal{a}.',
    ['Ať se lidé baví', { lid: 10, vir: -10 }], ['Masky zakázat', { vir: 10, lid: -10 }], ['Maškary jen bez kněží', { lid: 5, vir: 5, sil: -5 }], ['Daň z maškar', { fin: 5, lid: -5 }]),
  c('x3_ordal', 3, 'bisk', 'Kupce obvinili z krádeže. Biskup navrhuje Boží soud: ponese rozžhavené železo a když se mu ruka do tří dnů zahojí, je nevinný.',
    ['Boží soud', { vir: 10, ved: -10 }], ['Vyslechnout svědky', { ved: 5, lid: 5, vir: -5 }], ['Ať zaplatí pokutu', { fin: 5, lid: -5 }], ['Pustit ho', { dip: 5, sil: -5 }]),
  c('x3_hodiny', 3, 'alch', 'Sestrojil jsem hodiny, které samy odbíjejí čas a ukazují, kde je slunce a měsíc. Patřily by na radniční věž, {osl}.',
    ['Na radnici', { ved: 10, lid: 5, fin: -10 }], ['Na kostelní věž', { vir: 5, ved: 5, fin: -10 }], ['Jsou to čáry', { vir: 5, ved: -10 }], ['Prodat je do ciziny', { fin: 10, dip: 5, ved: -10 }]),
  c('x3_mongolove', 3, 'ryt', 'Z východu se valí jezdci, kteří vypálili celé země. Uherský král prosí o pomoc. Když padne on, budeme na řadě my.',
    ['Poslat vojsko', { dip: 10, sil: -10 }], ['Opevnit hranice', { sil: 10, fin: -10, dip: -5 }], ['Jet osobně v čele', { sil: 5, vir: 5, lid: -10 }], ['Vyjednávat s chánem', { dip: 5, vir: -10, fin: -5 }]),

  // ── Novověk ───────────────────────────────────────────
  c('x4_porcelan', 4, 'vyn', 'Přišla jsem na tajemství bílého porcelánu, který se dosud vozil z Číny! Manufaktura by vydělala jmění. Saští špioni už se vyptávají.',
    ['Postavit manufakturu', { fin: 10, ved: 5, pri: -10 }], ['Tajemství přísně střežit', { sil: 5, ved: -5, fin: 5 }], ['Darovat servis císaři', { dip: 10, fin: -5 }], ['Prodat recept Sasům', { fin: 10, dip: -5, ved: -10 }]),
  c('x4_robota', 4, 'rev', 'Sedláci pořád musejí tři dny v týdnu robotovat na panském. Ve vsích se mluví o vzpouře. Zruš robotu, {osl}!',
    ['Zrušit robotu', { lid: 15, fin: -10, sil: -5 }], ['Omezit ji na dva dny', { lid: 5, fin: -5 }], ['Vykoupit ji penězi', { fin: 5, lid: -5 }], ['Vzpouru potlačit', { sil: 10, lid: -15 }]),
  c('x4_loterie', 4, 'hrabe', 'Pokladna je prázdná, {osl}. Navrhuji státní loterii. Lidé rádi sázejí – a zisk připadne koruně. Kněží tomu říkají hazard.',
    ['Spustit loterii', { fin: 10, vir: -10 }], ['Výnos na sirotčince', { fin: 5, lid: 5, vir: -5, sil: -5 }], ['Hazard zakázat', { vir: 5, fin: -10 }], ['Zvýšit daně', { fin: 10, lid: -10 }]),
  c('x4_chronometr', 4, 'kap', 'Jeden hodinář sestrojil chronometr, se kterým na moři určím přesnou polohu. Konec ztroskotání! Chce za něj ale celou odměnu.',
    ['Zaplatit mu', { ved: 10, fin: -10 }], ['Nejdřív zkouška', { ved: 5, dip: -5 }], ['Ať ho vyrábí pro flotilu', { sil: 5, dip: 5, fin: -10 }], ['Hodinář není astronom', { fin: 5, ved: -10 }]),
  c('x4_tolerance', 4, 'hrabe', 'Evangelíci se stále modlí potají ve stodolách. Rakouský císař už povolil jiné víry. Vydáme toleranční patent?',
    ['Svoboda vyznání', { lid: 10, dip: 5, vir: -10 }], ['Jedna víra, jedna země', { vir: 10, lid: -10 }], ['Modlitebny bez věží', { lid: 5, vir: -5 }], ['Ať se vystěhují', { vir: 5, dip: -10, fin: -5 }]),
  c('x4_pozar', 4, 'tov', 'Velký požár strávil celé předměstí. Stovky lidí jsou bez střechy. Já bych tam postavil novou čtvrť z cihel – a pozemky levně koupil.',
    ['Prodat mu pozemky', { fin: 10, lid: -10 }], ['Stavět za státní peníze', { lid: 10, fin: -15 }], ['Zavést hasičský sbor', { lid: 5, sil: 5, fin: -10 }], ['Jen dřevo, ať se staví', { fin: 5, pri: -10 }]),
  c('x4_cisla', 4, 'hrabe', 'Na každý dům bych dal číslo a spočítal všechny muže schopné služby. Konečně bychom věděli, kolik máme vojáků – i daňových poplatníků.',
    ['Očíslovat všechno', { sil: 10, fin: 5, lid: -10 }], ['Jen pro poštu', { ved: 5, dip: 5, sil: -5 }], ['Lidé nejsou čísla', { lid: 5, sil: -10 }], ['Čísla i na šlechtu', { lid: 10, dip: -5, fin: -5 }]),
  c('x4_opera', 4, 'hrabe', 'Mladý skladatel z Vídně chce u nás uvést novou operu. Vídeňáci ho prý nedocenili. Divadlo by to však stálo celou sezónu.',
    ['Velká premiéra', { dip: 10, lid: 5, fin: -10 }], ['Opera v němčině', { dip: 5, lid: -5 }], ['Opera česky', { lid: 10, dip: -5, fin: -5 }], ['Raději lidové písně', { lid: 5, ved: -5 }]),
  c('x4_cukr', 4, 'kap', 'Na ostrovech, kde sázíme cukrovou třtinu, pracují otroci v řetězech. V Anglii už se o tom mluví nahlas. Co s plantážemi, {osl}?',
    ['Zrušit otroctví', { vir: 10, lid: 5, fin: -15 }], ['Plantáže zachovat', { fin: 15, vir: -10, dip: -5 }], ['Cukr z řepy doma', { ved: 10, pri: -5, fin: -5 }], ['Prodat ostrovy', { fin: 10, dip: -5, sil: -5 }]),
  c('x4_plyn', 4, 'vyn', 'Ze svítiplynu dokážu rozsvítit celé ulice. Žádné svíčky, žádná tma! Potrubí ale povede pod každým domem a umí vybuchnout.',
    ['Rozsvítit město', { ved: 10, lid: 5, fin: -10 }], ['Jen hlavní třída', { ved: 5, fin: -5 }], ['Příliš nebezpečné', { lid: 5, ved: -10 }], ['Ať zaplatí kavárny', { fin: 5, lid: -5, ved: 5 }]),
  c('x4_akcie', 4, 'tov', 'Zakládám akciovou společnost na průplav k moři, {osl}. Akcie rostou každý den! Kdyby koruna koupila podíl, zbohatneme všichni.',
    ['Koupit velký podíl', { fin: 10, lid: -5, dip: -5 }, { next: 'x4_akcie2', in: 4 }], ['Nevěřím tomu', { fin: -5, ved: 5 }], ['Ať kupují občané', { fin: 5, lid: 5, sil: -5 }, { next: 'x4_akcie2', in: 4 }], ['Spekulaci zdanit', { fin: 5, dip: -5 }]),
  c('x4_akcie2', 4, 'tov', 'Bublina praskla. Průplav se nikdy nekopal a akcie nemají cenu ani papíru. Před mou kanceláří stojí rozzuřený dav, {osl}.',
    ['Kraus půjde do vězení', { lid: 10, fin: -5 }], ['Nahradit lidem ztráty', { lid: 10, fin: -15 }], ['Rozehnat dav', { sil: 5, lid: -10 }], ['Zákon o bankách', { ved: 5, fin: 5, dip: -5 }], Q),
  c('x4_verbiri', 4, 'rev', 'Verbíři opíjejí mladíky v hospodách a ráno je odvádějí na vojnu. Matky pláčou u brány kasáren, {osl}.',
    ['Zakázat verbování', { lid: 10, sil: -10 }], ['Armáda potřebuje muže', { sil: 10, lid: -10 }], ['Jen dobrovolníci', { lid: 5, sil: -5, fin: -5 }], ['Odvod losem', { sil: 5, lid: -5, vir: 5 }]),

  // ── Moderní doba ──────────────────────────────────────
  c('x5_panelaky', 5, 'inz', 'Lidé bydlí v suterénech a ve sklepích. Z betonových panelů postavím sídliště za pár let – jenže všechny domy budou vypadat stejně.',
    ['Sídliště pro všechny', { lid: 10, fin: -10, pri: -5 }], ['Cihlové domy pomalu', { pri: 5, lid: -5 }], ['Sídliště i s parky', { lid: 5, pri: 5, fin: -15 }], ['Ať si staví sami', { fin: 5, lid: -10 }]),
  c('x5_film', 5, 'novin', 'Mladý režisér natočil film o zbabělém důstojníkovi. Generál ho chce zakázat, ale v Benátkách film vyhrál cenu, {osl}.',
    ['Uvést ho v kinech', { lid: 10, dip: 5, sil: -10 }], ['Zakázat film', { sil: 5, lid: -10, dip: -5 }], ['Vystřihnout pár scén', { sil: 5, ved: -5 }], ['Uvést jen v cizině', { dip: 5, lid: -5 }]),
  c('x5_spion', 5, 'genl', 'Zatkli jsme slavného spisovatele. Má doma vysílačku a šifry pro cizí rozvědku. Polovina národa ho miluje, {osl}.',
    ['Veřejný soud', { sil: 5, lid: -5, dip: -5 }, { next: 'x5_spion2', in: 3 }], ['Vyměnit ho za našeho', { dip: 10, sil: -5 }], ['Krmit je lživými zprávami', { sil: 10, dip: -5, ved: -5 }], ['Tiše ho propustit', { lid: 5, sil: -10 }]),
  c('x5_spion2', 5, 'novin', 'Na soudu se ukázalo, že vysílačku do bytu spisovateli někdo podstrčil. Novináři se ptají, kdo z generálova štábu to byl.',
    ['Vyšetřit generála', { lid: 10, sil: -10 }], ['Případ uzavřít', { sil: 5, lid: -10 }], ['Omluvit se mu', { lid: 5, dip: 5, sil: -5 }], ['Novináře umlčet', { sil: 5, ved: -5, lid: -10 }], Q),
  c('x5_elektrina', 5, 'inz', 'Ve městech svítí žárovky, ale na vesnicích se pořád svítí petrolejkou. Natáhnout dráty do každé vsi stojí horu peněz.',
    ['Elektřinu každé vsi', { lid: 10, ved: 5, fin: -15 }], ['Jen velké obce', { fin: -5, lid: 5, ved: -5 }], ['Ať platí obce samy', { fin: 5, lid: -10 }], ['Malé vodní elektrárny', { pri: -5, ved: 5, fin: -5 }]),
  c('x5_znarodneni', 5, 'novin', 'Majitelé velkých továren vyvážejí peníze do ciziny. Dělníci chtějí továrny znárodnit, vlastníci hrozí soudem v zahraničí.',
    ['Znárodnit vše', { lid: 10, fin: -10, dip: -10 }], ['Jen doly a banky', { lid: 5, fin: 5, dip: -5, ved: -5 }], ['Zdanit vývoz peněz', { fin: 10, dip: -5 }], ['Nechat trh být', { fin: 5, lid: -10 }]),
  c('x5_listky', 5, 'genl', 'Válka zdražila všechno a v obchodech dochází chléb. Zavedeme potravinové lístky, {osl}? Hned by vznikl černý trh.',
    ['Lístky pro všechny', { lid: 5, sil: 5, fin: -10 }], ['Pevné ceny', { lid: 5, fin: -5, ved: -5 }], ['Nejdřív armáda', { sil: 10, lid: -10 }], ['Dovoz ze zámoří', { dip: 5, fin: -10, lid: 5 }]),
  c('x5_emigrace', 5, 'dipl', 'Naši nejlepší fyzici odcházejí za oceán, kde jim platí desetkrát víc. Brzy tu nebude nikdo, kdo umí postavit reaktor.',
    ['Zvýšit jim platy', { ved: 10, fin: -10 }], ['Zakázat vycestování', { ved: 5, lid: -10, dip: -5 }], ['Přilákat cizí vědce', { ved: 5, dip: 5, lid: -5 }], ['Ať jdou', { fin: 5, ved: -10 }]),
  c('x5_ddt', 5, 'inz', 'Nový postřik DDT vyhubí komáry i škůdce na polích. Úroda roste. Jenže u rybníků prý mizí ptáci a jejich vajíčka praskají.',
    ['Stříkat všude', { fin: 10, lid: 5, pri: -15 }], ['Zakázat postřik', { pri: 10, fin: -10 }], ['Jen proti malárii', { lid: 5, pri: -5 }], ['Výzkum dopadů', { ved: 10, fin: -5, lid: -5 }]),
  c('x5_doping', 5, 'novin', 'Naše běžkyně vyhrála zlato, ale soupeřky tvrdí, že brala povzbuzující pilulky. Trenér mlčí, národ jásá, {osl}.',
    ['Nechat to vyšetřit', { dip: 10, lid: -10 }], ['Hájit ji', { lid: 10, dip: -10 }], ['Vrátit medaili', { dip: 5, vir: 5, lid: -10 }], ['Vlastní testy pro všechny', { ved: 5, fin: -5, lid: -5 }]),
  c('x5_ropa', 5, 'dipl', 'Ropné země uvalily embargo. Benzín došel, u pump stojí fronty přes celé město a doprava kolabuje, {osl}.',
    ['Neděle bez aut', { pri: 5, lid: -10 }], ['Koupit ropu draze', { fin: -15, lid: 5, dip: 5 }], ['Těžit doma uhlí', { fin: 5, pri: -10, sil: 5 }], ['Jaderné elektrárny', { ved: 10, fin: -10, pri: -5 }]),
  c('x5_parada', 5, 'genl', 'Výročí republiky! Chci uspořádat vojenskou přehlídku s tanky přes celé náměstí. Ať svět vidí, že se umíme bránit.',
    ['Velká přehlídka', { sil: 10, fin: -5, dip: -5 }], ['Lidová slavnost', { lid: 10, sil: -5 }], ['Přehlídka i hostů', { dip: 10, fin: -10 }], ['Peníze na školy', { ved: 5, sil: -10, lid: 5 }]),
  c('x5_samoobsluha', 5, 'novin', 'Otevřela první samoobsluha. Lidé si sami berou zboží z regálů a nakupují za polovinu času. Malí kupci píšou, že je to jejich konec.',
    ['Samoobsluhy všude', { fin: 10, lid: 5, vir: -10 }], ['Chránit malé obchody', { lid: 5, fin: -10 }], ['Daň pro velké řetězce', { fin: 5, dip: -5, lid: 5, ved: -5 }], ['Družstevní obchody', { lid: 10, fin: -5, sil: -5 }]),

  // ── Současnost ────────────────────────────────────────
  c('x6_robotaxi', 6, 'tech', 'Moje auto bez řidiče srazilo v noci cyklistu. Je to první nehoda za milion kilometrů, {osl}. Nesmíte zastavit pokrok kvůli jedné chybě.',
    ['Zastavit provoz', { lid: 5, ved: -10, fin: -5 }], ['Pokračovat dál', { fin: 10, ved: 5, lid: -15 }], ['Přísné testy', { ved: 5, lid: 5, fin: -5 }], ['Odškodnění rodině', { lid: 5, fin: -10 }]),
  c('x6_bydleni', 6, 'infl', 'Mladí si nemůžou koupit byt ani za třicet let práce. Moje video o tom vidělo dva miliony lidí. Kdy s tím vláda něco udělá, {osl}?',
    ['Stavět obecní byty', { lid: 10, fin: -15 }], ['Zdanit prázdné byty', { lid: 5, fin: 5, dip: -5 }], ['Zrychlit povolení', { fin: 5, pri: -10, lid: 5 }], ['Trh se srovná', { fin: 5, lid: -10 }]),
  c('x6_raketa', 6, 'tech', 'Chci u nás postavit kosmodrom pro turisty. Lety na oběžnou dráhu pro boháče! Každý start ale spálí tolik paliva jako město za rok.',
    ['Postavit kosmodrom', { fin: 10, ved: 5, pri: -15 }], ['Jen vědecké lety', { ved: 10, fin: -5, pri: -5 }], ['Ekologická daň', { fin: 5, pri: 5, dip: -5, ved: -5 }], ['Ani náhodou', { pri: 5, ved: -5, fin: -5 }]),
  c('x6_plasty', 6, 'klim', 'Na dně oceánu leží plastové tašky a ryby mají v žaludku mikroplasty. Zakažme jednorázové plasty, {osl}.',
    ['Zákaz plastů', { pri: 10, fin: -10 }], ['Zálohovat lahve', { pri: 5, lid: -5 }], ['Výzkum nových obalů', { ved: 10, fin: -10 }], ['Recyklace stačí', { fin: 5, pri: -10 }]),
  c('x6_deepfake', 6, 'infl', 'Koluje video, kde údajně ty, {osl}, urážíš sousední zemi. Je to podvrh vyrobený umělou inteligencí, ale vypadá jako pravé.',
    ['Vysvětlit to živě', { lid: 5, vir: 5, fin: -5 }, { next: 'x6_deepfake2', in: 3 }], ['Žalovat autory', { sil: 5, lid: -5 }], ['Omluvit se sousedům', { dip: 10, lid: -10 }], ['Zákon proti podvrhům', { ved: 5, sil: 5, lid: -10 }, { next: 'x6_deepfake2', in: 3 }]),
  c('x6_deepfake2', 6, 'tech', 'Stopa podvrženého videa vede k farmě falešných účtů v zahraničí. Moje firma umí podvrhy poznat automaticky – za státní zakázku.',
    ['Dát mu zakázku', { ved: 10, fin: -10 }], ['Vyhostit diplomaty', { sil: 5, dip: -10 }], ['Vzdělávat lidi', { ved: 5, lid: 5, fin: -10 }], ['Nechat to plavat', { fin: 5, vir: -10 }], Q),
  c('x6_kamery', 6, 'tech', 'Mám systém, který podle tváře pozná každého na ulici. Zločinnost klesne na nulu. Stačí kamery na každém rohu, {osl}.',
    ['Kamery všude', { sil: 10, lid: -10, fin: -5 }], ['Jen na letištích', { sil: 5, dip: 5, fin: -5 }], ['Zakázat rozpoznávání', { lid: 10, sil: -5, ved: -5 }], ['Pilotní projekt', { ved: 5, fin: -5 }]),
  c('x6_maso', 6, 'klim', 'Firma vypěstovala hovězí z buněk v laboratoři – bez krav, skoro bez emisí. Zemědělci protestují traktory před parlamentem.',
    ['Podpořit maso z laboratoře', { pri: 10, ved: 5, lid: -10 }], ['Zakázat ho', { lid: 5, ved: -10 }], ['Označit jako umělé', { lid: 5, fin: -5 }], ['Dotace pro farmáře', { lid: 10, fin: -10, pri: -5 }]),
  c('x6_ctyri_dny', 6, 'infl', 'Firmy, které zkusily čtyřdenní pracovní týden, mají spokojenější a stejně výkonné lidi. Moji sledující to chtějí všude, {osl}!',
    ['Zákonem pro všechny', { lid: 15, fin: -10 }], ['Nejdřív na úřadech', { lid: 5, fin: -5 }], ['Ať se domluví firmy', { fin: 5, lid: -5 }], ['Daňová úleva firmám', { lid: 5, fin: -10, ved: 5 }]),
  c('x6_kurovec', 6, 'klim', 'Kůrovec sežral půlku smrkových lesů a suché stromy hoří jako troud. Lesníci chtějí kácet, já bych nechala les obnovit sám.',
    ['Vykácet a prodat', { fin: 10, pri: -10 }], ['Nechat les přírodě', { pri: 10, fin: -10 }], ['Sázet smíšený les', { pri: 5, lid: 5, fin: -10 }], ['Víc hasičů', { sil: 5, lid: 5, fin: -10 }]),
  c('x6_datacentrum', 6, 'tech', 'Postavím u vás datové centrum pro umělou inteligenci. Spotřebuje tolik elektřiny jako půl milionu domácností a chlazení vypije řeku.',
    ['Vítejte', { fin: 10, ved: 5, pri: -15 }], ['Jen se zelenou energií', { pri: 5, fin: -5, ved: 5 }], ['Teplo do sítě města', { lid: 5, pri: 5, fin: -10 }], ['Ať jde jinam', { pri: 5, ved: -10 }]),
  c('x6_kandidatka', 6, 'infl', 'Rozhodla jsem se kandidovat do parlamentu, {osl}! Mám víc sledujících než všechny strany dohromady. Podpoříte mě?',
    ['Podpořit ji', { lid: 10, vir: -10 }], ['Varovat před ní', { vir: 5, lid: -10 }], ['Nabídnout jí ministerstvo', { lid: 5, sil: -5, ved: -5 }, { rel: { infl: 1 } }], ['Mlčet', { sil: 5, lid: -5 }]),
  c('x6_geny', 6, 'tech', 'Moji vědci umějí upravit geny embrya, aby se dítě nenarodilo s vrozenou nemocí. Někteří rodiče už chtějí i barvu očí a vyšší IQ.',
    ['Jen proti nemocem', { ved: 10, vir: -5, fin: -5 }], ['Úplně zakázat', { vir: 10, ved: -10 }], ['Volný trh', { fin: 10, ved: 5, vir: -15 }], ['Etická komise', { ved: 5, lid: -5 }]),
];
