// Výpravy hrdinů: hrozby v krajích a kroky výpravy.
// Každá volba je riskantní čin testovaný jednou vlastností hrdiny (d20 + 2×vlastnost proti 11 + d).
// Hra vylosuje 3 kroky dané hrozby a seřadí je podle indexu: rané kroky = průzkum, pozdní = střet.
// Zástupné znaky: {hrdina} jméno hrdiny, {kraj} jméno kraje, {a} ženská koncovka.
// Texty jsou nadčasové – mohou se odehrát v pravěku stejně jako roku 2089.

const S = 'sila', O = 'obratnost', D = 'duvtip', C = 'charisma';
const o = ([t, a, d, ok, bad]) => ({ t, a, d, ok, bad });
const s = (id, text, l, r, u, d) => ({ id, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) } });

// ── Hrozby ─────────────────────────────────────────────
export const THREATS = {
  bandits: { name: 'Bandité', icon: 'crisis',
    text: 'Na stezkách v kraji {kraj} řádí tlupa banditů. Přepadají poutníky, pálí statky a lidé se bojí vyjít za tmy.',
    win: 'Tlupa je rozprášena a stezky v kraji {kraj} jsou znovu bezpečné. Lidé skládají písně o hrdinovi jménem {hrdina}.',
    lose: 'Bandité se v kraji {kraj} zabydleli. Statky pustnou a lidé platí výpalné místo dávek.' },
  beast: { name: 'Šelma', icon: 'crisis',
    text: 'V kraji {kraj} se z hvozdu vynořila obrovská šelma. Rve dobytek, strhává ploty a pastýři mluví o démonovi.',
    win: 'Šelma padla a její kůže visí nad branou. Kraj {kraj} si znovu troufá vyhnat stáda na pastvu.',
    lose: 'Šelma dál obchází kraj {kraj}. Lidé zavírají okenice a celé osady se stěhují pryč.' },
  plague: { name: 'Nákaza', icon: 'crisis',
    text: 'Kraj {kraj} sužuje podivná nákaza. Nemocní hoří horečkou, studny jsou podezřelé a sousedé se navzájem obviňují.',
    win: 'Zdroj nákazy je odhalen a ucpán. Kraj {kraj} pohřbívá své mrtvé, ale nemocných ubývá.',
    lose: 'Nákaza se z kraje {kraj} šíří dál. Lidé utíkají a odnášejí ji s sebou.' },
  revolt: { name: 'Vzpoura', icon: 'crisis',
    text: 'V kraji {kraj} se lidé vzbouřili. Vyhnali správce, obsadili sýpky a jejich vůdce slibuje svět bez pánů.',
    win: 'Vzpoura v kraji {kraj} utichla bez velkého krveprolití. Lidé se vrátili k práci a pamatují si, kdo s nimi mluvil.',
    lose: 'Kraj {kraj} se vymkl z rukou. Vzbouřenci drží sýpky a jejich hlas se nese do dalších krajů.' },
  cult: { name: 'Tajný kult', icon: 'crisis',
    text: 'V kraji {kraj} mizí lidé. Šeptá se o tajném kultu, který se schází v noci a klaní se něčemu pod zemí.',
    win: 'Kult je rozprášen a jeho úkryt zasypán. Zmizelí, kteří přežili, se vracejí domů k rodinám.',
    lose: 'Kult v kraji {kraj} sílí. Jeho znamení se objevují na zdech a nikdo už nemluví nahlas.' },
  treasure: { name: 'Ztracený poklad', icon: 'crisis',
    text: 'V kraji {kraj} našel pastevec úlomek staré mapy. Vede prý k pokladu, který dávní lidé ukryli před koncem světa.',
    win: 'Poklad je nalezen! {hrdina} se vrací s bohatstvím, o kterém kraj {kraj} bude vyprávět celé věky.',
    lose: 'Poklad zůstal ztracen, nebo ho odnesl někdo jiný. Zbyla jen roztrhaná mapa a prázdné ruce.' },
};

// ── Kroky výprav ───────────────────────────────────────
export const QUEST_STEPS = {
  bandits: [
    s('q_bandits_1', '{hrdina} dorazil{a} do vypálené osady. Přeživší se krčí v troskách a nedůvěřivě hledí na každého cizince.',
      ['Vyptat se přeživších', C, 0, 'Stará žena prozradí, kudy bandité odtáhli a kolik jich je.', 'Lidé mlčí. Mají cizince za dalšího z banditů.'],
      ['Prohledat spáleniště', D, 1, 'V popelu leží ztracený odznak – bandité nosí znamení vlčí hlavy.', 'Popel nic neprozradil a čas utekl mezi prsty.'],
      ['Sledovat stopy', O, 2, 'Stopy vedou k lesu a {hrdina} je neztratí ani v potoce.', 'Stopy se rozplynuly na kamenité stráni.'],
      ['Zvednout trosky domu', S, -1, 'Pod trámem je živý chlapec. Vděčně vypráví všechno, co viděl.', 'Trám se zřítil a {hrdina} si poranil{a} ruku.']),
    s('q_bandits_2', 'Na stezce stojí opuštěný vůz, převržený a vyrabovaný. V křoví kolem je až příliš velké ticho.',
      ['Proplížit se kolem', O, 1, '{hrdina} proklouzl{a} křovím a za ním našel{a} spícího hlídače.', 'Prasklá větev prozradila každý krok. Šípy zasvištěly kolem.'],
      ['Prohlédnout vůz', D, 0, 'Ve dvojitém dně je seznam jmen – bandité mají v kraji spojence.', 'Vůz byl past. Z křoví vyběhli tři muži a {hrdina} jen taktak unikl{a}.'],
      ['Zavolat do křoví', C, 2, 'Mladý bandita vyleze a vzdá se. Prý už má toho života dost.', 'Odpovědí byl jen smích a kámen, který zasáhl rameno.'],
      ['Vtrhnout do houští', S, 3, 'Dva číhající bandité leží na zemi dřív, než stihli tasit zbraně.', 'Bylo jich víc, než se zdálo. {hrdina} musel{a} krvácející ustoupit.']),
    s('q_bandits_3', 'V hostinci u brodu sedí muž s vlčí hlavou vytetovanou na zápěstí. Pije sám a nespouští oči ze dveří.',
      ['Opít ho a vyzpovídat', C, 1, 'Po třetím džbánu muž vyklopí, kde má tlupa svůj tábor.', 'Muž prohlédl lest a zmizel oknem.'],
      ['Ukrást mu měšec', O, 2, 'V měšci je kus kůže s nákresem cesty k úkrytu.', 'Muž sevřel zlodějskou ruku a celý hostinec se otočil.'],
      ['Sledovat ho do noci', D, 0, 'Muž nevědomky vede k tajné stezce do hor.', 'Ve tmě se ztratil – a možná teď ví, že ho někdo sleduje.'],
      ['Přirazit ho ke zdi', S, 3, 'Pod tlakem muž vyzradí jména, hesla i počet stráží.', 'Muž vytáhl nůž a hospoda se proměnila ve rvačku.']),
    s('q_bandits_4', 'Tábor banditů leží v rokli. Hoří ohně, stráže se střídají a v ohradě drží zajatce z okolních vsí.',
      ['Osvobodit zajatce', O, 2, 'Zajatci tiše mizí do tmy a bandité přišli o rukojmí.', 'Řetězy zařinčely. Celý tábor je vzhůru.'],
      ['Podpálit zásoby', D, 1, 'Zásoby hoří a bandité se v chaosu perou mezi sebou.', 'Oheň se obrátil s větrem a málem pohltil i samotného vetřelce.'],
      ['Přidat se jako nováček', C, 3, '{hrdina} je přijat{a} do tlupy a vidí všechno zevnitř.', 'Vůdce poznal vetřelce. Následoval útěk o život.'],
      ['Vyřadit hlídku', S, 0, 'Hlídka u vchodu tiše padla a cesta do tábora je volná.', 'Hlídka stihla zatroubit na poplach.']),
    s('q_bandits_5', 'Vůdce banditů, obr s jizvou přes tvář, vyšel před tábor. {hrdina} je vyzván{a} na souboj jeden na jednoho.',
      ['Přijmout souboj', S, 3, 'Po dlouhém zápasu vůdce padá do prachu a tlupa se rozutíká.', 'Vůdce byl silnější. {hrdina} odchází zbit{a} a ponížen{a}.'],
      ['Uhýbat a unavit ho', O, 2, 'Vůdce se vyčerpal a zakopl o vlastní zbraň.', '{hrdina} uklouzl{a} a dostal{a} ránu, na kterou nezapomene.'],
      ['Poštvat tlupu proti němu', C, 1, 'Bandité si vzpomněli na nespravedlivé dělení kořisti a obrátili se proti vůdci.', 'Tlupa stojí pevně za vůdcem a slova cizince zní jako lež.'],
      ['Nastražit past', D, 0, 'Vůdce vstoupil do oka nastražené smyčky a visí hlavou dolů.', 'Vůdce past prohlédl a vysmál se jí.']),
    s('q_bandits_6', 'Zbytek tlupy se zabarikádoval v jeskyni. Mají vodu, zbraně a nic, co by mohli ztratit.',
      ['Vyhladovět je', D, 0, 'Po třech dnech vycházejí vyhladovělí a odevzdávají zbraně.', 'Jeskyně měla druhý východ. Půlka tlupy utekla.'],
      ['Nabídnout milost', C, 1, 'Bandité vyměnili zbraně za život a slib, že odejdou z kraje.', 'Milost odmítli a odpověděli kameny.'],
      ['Vylézt skalou shora', O, 2, '{hrdina} sešplhal{a} komínem a překvapil{a} je zezadu.', 'Skála se odlomila a {hrdina} se zřítil{a} na zem.'],
      ['Prorazit barikádu', S, 4, 'Barikáda povolila a bandité se vzdávají jeden po druhém.', 'Barikáda vydržela a z jeskyně se snesla sprška kamení.']),
  ],

  beast: [
    s('q_beast_1', 'Na pastvině leží roztrhaný dobytek. Stopy jsou větší než lidská dlaň a vedou různými směry.',
      ['Prozkoumat zdechliny', D, 0, 'Šelma žere jen srdce. Loví v noci a vrací se ke kořisti.', 'Pach zdechlin otupil smysly a nic se nedozvěděl{a}.'],
      ['Vyslechnout pastýře', C, -1, 'Pastýř šelmu viděl: chodí od bažin a bojí se ohně.', 'Pastýř je tak vyděšený, že mluví jen o démonech.'],
      ['Sledovat nejčerstvější stopu', O, 2, 'Stopa vede k bažině a k ohlodaným kostem pod skalou.', 'Stopa vede do trní a {hrdina} se v něm zamotal{a}.'],
      ['Odtáhnout mrtvé kusy', S, 1, 'Zdechliny jsou spáleny a šelma přijde o snadnou potravu.', 'Zdechlina byla těžší, než se zdálo. Záda bolí ještě dny.']),
    s('q_beast_2', 'Lovci z vesnice se chtějí přidat. Jsou odvážní, ale hluční a neukáznění. Šelmu by spíš vyplašili.',
      ['Vycvičit je', C, 1, 'Lovci poslouchají a tvoří ukázněnou skupinu.', 'Lovci se urazili a odešli lovit sami.'],
      ['Poslat je domů', C, -1, 'Lovci odcházejí a {hrdina} může pokračovat nerušeně.', 'Lovci odcházejí s nadávkami a pomlouvají cizince po celé vsi.'],
      ['Naučit je stopovat', D, 2, 'Lovci se učí rychle a jejich oči teď pomáhají.', 'Lovci nepochopili nic a dupou po stopách.'],
      ['Ukázat jim sílu', S, 2, 'Po přetahování lan je jasné, kdo velí. Lovci se podřídí.', '{hrdina} prohrál{a} a lovci se smějí.']),
    s('q_beast_3', 'Bažina páchne hnilobou. Mezi stromy jsou zlomené kmeny a ve vzduchu visí zvláštní nažloutlá mlha.',
      ['Přeskákat po kamenech', O, 2, '{hrdina} se dostal{a} hluboko do bažiny bez jediného šplouchnutí.', 'Kámen se překotil a {hrdina} zapadl{a} do bahna po pás.'],
      ['Najít bezpečnou cestu', D, 1, 'Hladina řasy prozradila pevné dno a stezku k doupěti.', 'Cesta vedla do kruhu. Hodiny se ztratily v mlze.'],
      ['Brodit se napřímo', S, 0, 'Tvrdohlavě, ale bezpečně dorazil{a} k ostrůvku uprostřed.', 'Bahno sálo nohy a vyčerpalo všechny síly.'],
      ['Požádat poustevníka o radu', C, 1, 'Poustevník z bažiny ukáže brod a prozradí, že šelma má mláďata.', 'Poustevník schválně ukázal cestu do tůně.']),
    s('q_beast_4', 'Doupě šelmy je v jeskyni pod skalou. Uvnitř je slyšet hluboký dech a chroupání kostí.',
      ['Vylákat ji ven', D, 1, 'Šelma vyšla za návnadou na otevřené prostranství.', 'Šelma vycítila lest a zůstala ve tmě.'],
      ['Vplížit se dovnitř', O, 3, '{hrdina} je uvnitř a šelma spí. Okamžik překvapení je tu.', 'Šelma otevřela oči. Útěk byl jen o vlásek.'],
      ['Zavalit vchod', S, 2, 'Kameny uzavřely vchod. Šelma bude muset ven jinudy.', 'Kámen se sesunul na nohu a šelma se probudila.'],
      ['Zapálit oheň u vchodu', D, 0, 'Kouř vyhnal šelmu ven, oslepenou a zmatenou.', 'Vítr obrátil kouř a {hrdina} se dusí místo šelmy.']),
    s('q_beast_5', '{hrdina} stojí tváří v tvář šelmě. Je větší než kůň, oči jí žhnou a srst je zježená jako trny.',
      ['Postavit se jí', S, 4, 'Šelma narazila na neochvějnou sílu a padla.', 'Šelma jediným máchnutím odhodila protivníka stranou.'],
      ['Uskočit a zasáhnout bok', O, 2, 'Přesný zásah do boku šelmu zpomalil.', 'Uskočit nestačilo, drápy rozpáraly bok.'],
      ['Zkrotit ji pohledem', C, 3, 'Šelma se zastavila, sklopila uši a odešla do hvozdu.', 'Šelmu pohled jen rozzuřil.'],
      ['Zahnat ji do bažiny', D, 1, 'Šelma uvízla v bahně a je bezbranná.', 'Šelma se z bahna vyhrabala a zuřivější než předtím.']),
    s('q_beast_6', 'Zraněná šelma se stáhla k mláďatům. Brání je zuby nehty a za ní se krčí tři vyděšená štěňata.',
      ['Dorazit ji', S, 2, 'Šelma padla. Mláďata pozná kraj jen z vyprávění.', 'Šelma se vzepjala k poslednímu útoku a zasáhla drápy.'],
      ['Ukrást mláďata', O, 3, 'Bez mláďat šelma táhne pryč z kraje navždy.', 'Šelma to viděla. Její zuřivost nezná mez.'],
      ['Nechat je odejít', C, 0, 'Šelma s mláďaty mizí za hory a kraj si oddechne.', 'Lidé nevěří, že šelma odešla. Mluví o zbabělosti.'],
      ['Nastražit sítě', D, 1, 'Šelma i mláďata jsou chycena a odvlečena daleko.', 'Síť se roztrhla a šelma utekla do hvozdu.']),
  ],

  plague: [
    s('q_plague_1', 'U brány osady stojí stráže a nikoho nepouštějí. Z domů je slyšet kašel a nářek.',
      ['Přesvědčit stráže', C, 0, 'Stráže ustoupily a {hrdina} vstoupil{a} do nakažené osady.', 'Stráže zvedly zbraně. Cizincům tu nevěří.'],
      ['Přelézt hradbu', O, 1, '{hrdina} se dostal{a} dovnitř a nikdo si nevšiml.', 'Hradba byla kluzká a {hrdina} spadl{a} rovnou k nohám stráží.'],
      ['Pozorovat zvenku', D, -1, 'Zvenku je vidět, že nemocní jsou hlavně kolem jedné studny.', 'Z dálky nebylo vidět nic užitečného.'],
      ['Vyrazit bránu', S, 3, 'Brána povolila. Stráže pochopily, že tohle není obyčejný poutník.', 'Brána vydržela a {hrdina} strávil{a} noc v zajetí stráží.']),
    s('q_plague_2', 'Místní léčitelka tvrdí, že nákazu přinesli cizinci z hor. Dav se chystá vyhnat poslední rodinu přespolních.',
      ['Uklidnit dav', C, 2, 'Dav se rozešel. Rodina přespolních zůstává a je vděčná.', 'Dav se obrátil i proti cizímu zastánci.'],
      ['Prohlédnout nemocné', D, 1, 'Nákaza nepochází od cizinců – všichni pili z jedné studny.', 'Nemocní nic neprozradili a {hrdina} se nachladil{a}.'],
      ['Ukrýt rodinu', O, 1, 'Rodina je v bezpečí a může vyprávět, co viděla cestou.', 'Úkryt byl prozrazen a dav zuří ještě víc.'],
      ['Postavit se davu', S, 3, 'Dav ustoupil před pevným postojem a nikdo nebyl zraněn.', 'Dav byl silnější. Rodina musela utéct.']),
    s('q_plague_3', 'Ve sklepě léčitelky jsou podivné lahvičky a zápisky. Ona sama se vrací, každou chvíli.',
      ['Rychle přečíst zápisky', D, 1, 'Zápisky odhalují, že léčitelka ví o otrávené studni.', 'Písmo je nečitelné a čas utekl.'],
      ['Schovat se a čekat', O, 1, 'Léčitelka mluví sama se sebou a prozradí víc, než chtěla.', '{hrdina} kýchl{a} a byl{a} odhalen{a}.'],
      ['Počkat na ni a promluvit', C, 2, 'Léčitelka se rozpláče a přizná, že jí vyhrožovali.', 'Léčitelka křičí o zloději a sbíhají se sousedé.'],
      ['Zabavit lahvičky', S, 0, 'Lahvičky jsou v bezpečí. Možná obsahují lék.', 'Lahvička se rozbila a výpary na celé hodiny omámily smysly.']),
    s('q_plague_4', 'Studna, ze které pili nemocní, je zakrytá kamenem. Pod hladinou je cosi tmavého a páchnoucího.',
      ['Spustit se do studny', O, 3, 'Na dně leží zdechlina zatížená kamenem. Úmysl je jasný.', 'Lano prasklo a {hrdina} skončil{a} v ledové vodě.'],
      ['Odvalit kámen', S, 1, 'Studna je otevřená a hnilobný pach prozrazuje, co je uvnitř.', 'Kámen se nehnul a {hrdina} si natáhl{a} záda.'],
      ['Prozkoumat okolí', D, 0, 'Stopy vozu vedou od studny k mlýnu za vsí.', 'Okolí je ušlapané a stopy se ztrácejí.'],
      ['Vyslechnout dítě', C, 0, 'Dítě vidělo muže v kápi, jak tu v noci něco házel do vody.', 'Dítě se vylekalo a uteklo k matce.']),
    s('q_plague_5', 'Ve mlýnu za vsí sídlí bohatý mlynář. Prý zdražuje mouku – a za lék si říká o celé majetky.',
      ['Obvinit ho před lidmi', C, 2, 'Lidé uvěřili a mlynář je zatčen. Prozradil, kde ukrývá lék.', 'Mlynář je bohatý a lidé mu věří víc než cizinci.'],
      ['Najít důkazy ve mlýně', D, 1, 'Ve mlýně jsou zbytky stejných zdechlin jako ve studni.', 'Mlynář nechal důkazy zmizet včas.'],
      ['Vkrást se do sklepa', O, 2, 'Ve sklepě leží zásoby léku i deník s plány.', 'Psi ve mlýně spustili rámus a {hrdina} musel{a} utéct.'],
      ['Vytáhnout ho ven', S, 2, 'Mlynář před davem zbledl a přiznal se.', 'Mlynářovi pomocníci se vrhli do rvačky.']),
    s('q_plague_6', 'Lék je nalezen, ale nestačí pro všechny. Nemocných je stovky a každý den přibývají noví.',
      ['Vymyslet nový lék', D, 3, 'Z bylin a zbytku léku vznikla nová dávka pro všechny.', 'Pokus selhal a léčivo bylo promarněno.'],
      ['Rozdělit spravedlivě', C, 1, 'Lidé přijali dělení a nejslabší dostali lék první.', 'O lék se strhla rvačka a část vyšla nazmar.'],
      ['Donést lék do vzdálených vsí', O, 2, '{hrdina} doběhl{a} do všech vsí včas a zachránil{a} mnoho životů.', 'Cesta byla zrádná a část léku se rozlila.'],
      ['Zavřít ves a vydržet', S, 0, 'Ves zůstala uzavřená a nákaza se nerozšířila dál.', 'Lidé prolomili zátaras a nákaza se rozšířila.']),
  ],

  revolt: [
    s('q_revolt_1', 'Na náměstí stojí šibenice, na níž visí podobizna správce. Lidé se mračí na každého, kdo přišel zvenčí.',
      ['Promluvit s lidmi', C, 1, 'Lidé si stěžují na hlad a nespravedlivé dávky. Vzpoura má důvody.', 'Lidé se otočili zády a jeden plivl cizinci pod nohy.'],
      ['Vyslechnout v hostinci', D, 0, 'V hostinci se mluví o vůdci, kterému říkají Kovář.', 'Hostinský poznal zvědavé otázky a ukázal na dveře.'],
      ['Strhnout podobiznu', S, 2, 'Lidé zaváhali. Někdo má odvahu postavit se vzpouře.', 'Strhnutí podobizny vyvolalo rvačku.'],
      ['Nenápadně se rozhlédnout', O, -1, 'Za radnicí se schází skupina mladíků a cosi chystá.', '{hrdina} byl{a} rozpoznán{a} jako zvěd vrchnosti.']),
    s('q_revolt_2', 'Vzbouřenci obsadili sýpky a rozdávají obilí. Lidé jásají, ale zásoby brzy dojdou a zima je za dveřmi.',
      ['Varovat lidi', C, 2, 'Lidé začali šetřit a vzbouřenci zaváhali.', 'Lidé nechtějí slyšet o zimě, když mají plné žaludky.'],
      ['Spočítat zásoby', D, 0, 'Zásoby vydrží jen do mrazů. Vůdcové to vědí a mlčí.', 'Sýpky jsou střeženy a počítání se nedaří.'],
      ['Vkrást se do sýpky', O, 2, '{hrdina} zjistil{a}, že část obilí mizí na tajné vozy.', '{hrdina} byl{a} chycen{a} mezi pytli.'],
      ['Odvézt obilí do úkrytu', S, 3, 'Část obilí je v bezpečí pro zimní měsíce.', 'Vůz se převrhl a obilí se rozsypalo.']),
    s('q_revolt_3', 'Na shromáždění vzbouřenců mluví ohnivý řečník. Dav burácí a chce táhnout na sídlo vrchnosti.',
      ['Vystoupit a odporovat', C, 3, 'Dav naslouchá. Někteří začínají pochybovat.', '{hrdina} byl{a} vypískán{a} a málem ukamenován{a}.'],
      ['Zpochybnit řečníka otázkou', D, 1, 'Řečník se zakoktal a dav ztratil zápal.', 'Řečník otázku obratně otočil proti tazateli.'],
      ['Vytratit se a varovat', O, 0, 'Stráže jsou varovány a stihnou se připravit.', 'Odchod byl nápadný a pronásledovatelé byli rychlí.'],
      ['Strhnout řečníka', S, 2, 'Řečník spadl z bedny a dav se rozpadl ve zmatku.', 'Dav ochránil řečníka a {hrdina} byl{a} zbit{a}.']),
    s('q_revolt_4', 'Vůdce vzpoury, kterému říkají Kovář, souhlasí se schůzkou. Přijde ale jen s ozbrojenou družinou.',
      ['Vyjednat smír', C, 2, 'Kovář slibuje zastavit vzpouru, když se splní jeho požadavky.', 'Jednání se zvrhlo v urážky a hádku.'],
      ['Zjistit jeho slabinu', D, 1, 'Kovář má nemocnou dceru. To mění všechno.', 'Kovář je neprůhledný jako skála.'],
      ['Ukázat, že se nebojí', S, 2, 'Kovář si cení odvahy a mluví otevřeně.', 'Družina se postavila do obrany a schůzka skončila.'],
      ['Odhalit zrádce v družině', O, 3, 'Jeden z družiny posílá zprávy vrchnosti. Kovář je otřesen.', 'Obvinění se nepotvrdilo a {hrdina} teď vypadá jako štváč.']),
    s('q_revolt_5', 'Stráže vrchnosti se blíží k osadě. Chtějí vzpouru utopit v krvi. Vzbouřenci se chystají k boji.',
      ['Zastavit stráže', C, 3, 'Velitel stráží souhlasí s odkladem a krveprolití je odvráceno.', 'Velitel nevěří a dává rozkaz k útoku.'],
      ['Vyvést lidi do bezpečí', O, 1, 'Ženy a děti jsou ukryty v lese před bojem.', 'Útěk byl odhalen a lidé jsou rozptýleni.'],
      ['Postavit se mezi ně', S, 2, '{hrdina} stojí mezi oběma stranami a nikdo nechce udeřit první.', '{hrdina} byl{a} zasažen{a} a boj vypukl.'],
      ['Vymyslet lest', D, 1, 'Falešná zpráva odvedla stráže na druhou stranu kraje.', 'Lest byla prozrazena a obě strany zuří.']),
    s('q_revolt_6', 'Vzpoura se láme. Kovář je raněný, vzbouřenci se hádají a vrchnost žádá jeho hlavu.',
      ['Vyjednat milost', C, 2, 'Kovář je omilostněn a vzbouřenci odcházejí domů.', 'Vrchnost milost odmítla a vzbouřenci se cítí podvedeni.'],
      ['Ukrýt Kováře', O, 1, 'Kovář zmizel a vzpoura bez vůdce utichla.', 'Kovář byl nalezen a {hrdina} je obviněn{a} ze zrady.'],
      ['Zatknout ho sám', S, 3, 'Kovář je zatčen a vzpoura skončila bez dalšího boje.', 'Kovář se vzepřel a jeho lidé ho vysvobodili.'],
      ['Navrhnout nové dávky', D, 0, 'Spravedlivější dávky uklidní obě strany.', 'Návrh nikoho nenadchl a spory pokračují.']),
  ],

  cult: [
    s('q_cult_1', 'Rodina zmizelé dívky čeká u prahu. Matka drží v rukou podivný amulet, který dívka přinesla domů.',
      ['Prozkoumat amulet', D, 1, 'Amulet nese znamení oka pod zemí – stejné jako na staré kapli.', 'Amulet je obyčejný kámen. Nebo to tak aspoň vypadá.'],
      ['Utěšit matku', C, 0, 'Matka prozradí, že dívka chodila za mladým kazatelem.', 'Matka se rozplakala a nemůže mluvit.'],
      ['Prohledat dívčin pokoj', O, 0, 'Pod podlahou jsou dopisy s pozvánkou na noční setkání.', 'Pokoj je prázdný a otec vetřelce vyhodil.'],
      ['Vyhrožovat sousedům', S, 2, 'Soused vyklopil, že viděl dívku jít k lesu s pochodní.', 'Sousedé se semkli a nikdo nepromluví.']),
    s('q_cult_2', 'Mladý kazatel káže na návsi o konci světa a o tom, že spása přichází zespodu. Lidé ho poslouchají.',
      ['Nechat se získat', C, 2, '{hrdina} dostal{a} pozvání na noční obřad.', 'Kazatel cosi vycítil a změnil řeč.'],
      ['Chytit ho slovem', D, 1, 'Kazatel se zamotal do rozporů a lidé se mračí.', 'Kazatel je výmluvnější a {hrdina} vypadá hloupě.'],
      ['Sledovat ho domů', O, 1, 'Kazatel nevědomky vede k rozpadlé kapli na kopci.', 'Kazatel se otočil a zamával. Věděl to celou dobu.'],
      ['Umlčet ho', S, 3, 'Kazatel je zavřen ve sklepě a začíná mluvit.', 'Lidé se zastali kazatele a {hrdina} musel{a} ustoupit.']),
    s('q_cult_3', 'Rozpadlá kaple na kopci. Pod oltářem jsou schody do tmy a z hlubin stoupá zpěv.',
      ['Sestoupit potichu', O, 2, '{hrdina} se dostal{a} hluboko do podzemí nepozorován{a}.', 'Schod se ulomil a hluk se rozlehl podzemím.'],
      ['Rozluštit nápisy', D, 1, 'Nápisy varují před pastí a ukazují bezpečnou cestu.', 'Nápisy byly matoucí a {hrdina} šlápl{a} na propadlo.'],
      ['Počkat na kultisty', C, 1, 'Kultista s maskou se dal do řeči a vzal nováčka s sebou.', 'Kultista nevěřil a zalarmoval ostatní.'],
      ['Vylomit zamčenou mříž', S, 2, 'Mříž povolila a cesta je volná.', 'Mříž zaskřípala a zpěv dole utichl.']),
    s('q_cult_4', 'V podzemí je síň plná lidí v kápích. Zmizelí jsou připoutáni u zdi. Kněz kultu zvedá ruce k obřadu.',
      ['Přerušit obřad', C, 3, 'Hlas zahřměl síní a kultisté zaváhali.', 'Kultisté se otočili a vrhli se na vetřelce.'],
      ['Osvobodit zajatce', O, 2, 'Zajatci jsou volní a tiše mizí chodbou ven.', 'Řetěz zařinčel a kněz ukázal přímo na vetřelce.'],
      ['Zhasnout ohně', D, 1, 'Tma vyvolala paniku a kultisté se rozprchli.', 'Ve tmě se {hrdina} srazil{a} se stěnou.'],
      ['Probít se ke knězi', S, 4, 'Kněz je sražen k zemi a obřad je přerušen.', 'Kultistů bylo příliš mnoho. {hrdina} byl{a} zatlačen{a} zpět.']),
    s('q_cult_5', 'Kněz kultu stojí u propasti. Tvrdí, že bez obětí se probudí to, co dřímá dole, a pohltí celý kraj.',
      ['Odhalit jeho lež', D, 1, 'Kněz lhal. Dole je jen prázdná jeskyně a ozvěna.', 'Ze tmy se ozvalo cosi, co nikdo nedokáže vysvětlit.'],
      ['Přemluvit ho', C, 2, 'Kněz se zlomil a přiznal, že se bál.', 'Kněz se jen smál a skočil do propasti.'],
      ['Vrhnout se na něj', S, 2, 'Kněz je stržen od propasti a spoután.', 'Kněz uhnul a {hrdina} málem spadl{a} dolů.'],
      ['Strhnout mu amulet', O, 3, 'Bez amuletu kněz ztratil moc nad kultisty.', 'Amulet byl připoután a kněz se vyškubl.']),
    s('q_cult_6', 'Podzemí se otřásá. Strop se drolí a cesta ven se zavírá. Někteří kultisté stále zpívají.',
      ['Vyvést všechny ven', C, 2, 'Kultisté poslechli a všichni vyšli na světlo.', 'Kultisté odmítají odejít a {hrdina} musí utéct bez nich.'],
      ['Najít rychlou cestu', D, 1, 'Proud vzduchu prozradil únikovou chodbu.', 'Chodba končila zavalena kamením.'],
      ['Proběhnout troskami', O, 2, '{hrdina} proklouzl{a} padajícími kameny až ven.', 'Kámen zasáhl nohu a útěk byl bolestný.'],
      ['Podepřít strop', S, 3, 'Strop vydržel dost dlouho na to, aby všichni utekli.', 'Strop se zřítil a část lidí zůstala uvnitř.']),
  ],

  treasure: [
    s('q_treasure_1', 'Pastevec, který našel mapu, se zdráhá ji vydat. Tvrdí, že poklad patří jeho předkům.',
      ['Slíbit mu podíl', C, 0, 'Pastevec mapu vydal a přidal se jako průvodce.', 'Pastevec nevěří a mapu schoval.'],
      ['Ukrást mapu', O, 2, '{hrdina} má mapu a pastevec nic netuší.', 'Pastevec se probudil a spustil povyk.'],
      ['Okopírovat ji pohledem', D, 1, '{hrdina} si mapu zapamatoval{a} do poslední čárky.', 'Paměť zklamala a polovina mapy chybí.'],
      ['Vzít ji silou', S, 2, 'Mapa je zabavena. Pastevec odchází s kletbami.', 'Pastevec se bránil a mapa se roztrhla.']),
    s('q_treasure_2', 'Mapa je psána neznámými znaky. Jen stará bylinářka na samotě prý umí číst řeč dávných lidí.',
      ['Rozluštit sám', D, 3, 'Znaky se poddaly a ukazují cestu k vodopádu.', 'Znaky zůstaly záhadou a čas utekl.'],
      ['Požádat bylinářku', C, 1, 'Bylinářka přeložila mapu a varovala před pastmi.', 'Bylinářka chce za překlad víc, než je rozumné dát.'],
      ['Přinést jí dar z hor', O, 2, 'Vzácná květina z útesu obměkčila bylinářčino srdce.', 'Útes byl strmý a {hrdina} málem spadl{a}.'],
      ['Odnosit jí dřevo', S, 0, 'Bylinářka ocenila poctivou práci a mapu přeložila.', 'Dřeva bylo moc a síly došly dřív než práce.']),
    s('q_treasure_3', 'Cestu k pokladu přehradila rozvodněná řeka. Starý most je ztrouchnivělý a voda burácí.',
      ['Přeběhnout most', O, 2, 'Most vydržel a {hrdina} je na druhém břehu.', 'Prkno prasklo a {hrdina} skončil{a} ve vodě.'],
      ['Přeplavat proud', S, 3, 'Proud byl silný, ale {hrdina} vydržel{a}.', '{hrdina} byl{a} odnesen{a} daleko po proudu.'],
      ['Najít brod', D, 0, 'Kus po proudu se řeka rozlévá a je mělká.', 'Hledání trvalo celý den a brod nikde.'],
      ['Najmout převozníka', C, 1, 'Převozník za dobrý příběh převáží zdarma.', 'Převozník si vzal plat a zmizel bez převozu.']),
    s('q_treasure_4', 'U vodopádu tábořili jiní hledači pokladu. Mají stejnou mapu a jsou ozbrojení.',
      ['Spojit se s nimi', C, 1, 'Hledači souhlasí s dělením. Ve víc lidech je to bezpečnější.', 'Hledači se smějí a vyhánějí cizince.'],
      ['Předběhnout je', O, 2, '{hrdina} se dostal{a} k jeskyni dřív než soupeři.', 'Soupeři si všimli a začala honička.'],
      ['Navést je jinam', D, 1, 'Falešné stopy odvedly hledače na opačnou stranu.', 'Hledači lest prohlédli a jsou ostražitější.'],
      ['Zastrašit je', S, 3, 'Hledači odešli, protože nechtějí riskovat boj.', 'Hledači se postavili a {hrdina} musel{a} ustoupit.']),
    s('q_treasure_5', 'Za vodopádem je jeskyně. Podlaha je posetá dlaždicemi se znaky a v koutě leží kostry dřívějších hledačů.',
      ['Najít bezpečný vzor', D, 2, 'Vzor dlaždic se shoduje se znaky na mapě.', 'Dlaždice se propadla a {hrdina} jen taktak uskočil{a}.'],
      ['Přeskákat dlaždice', O, 3, '{hrdina} přeskákal{a} past bez dotyku země.', 'Ze zdí vylétly šipky a jedna zasáhla.'],
      ['Odtrhnout dlaždice', S, 1, 'Pod dlaždicemi jsou mechanismy, teď už neškodné.', 'Mechanismus se spustil a strop začal klesat.'],
      ['Poslat napřed průvodce', C, 0, 'Pastevec zná znaky předků a cestou provede.', 'Pastevec odmítl a vrací se domů.']),
    s('q_treasure_6', 'Poklad leží v hrobce dávného vládce. Truhla je těžká a dveře se zavírají, jakmile se jí někdo dotkne.',
      ['Vytáhnout truhlu', S, 3, 'Truhla je venku a dveře se zavřely až za ní.', 'Truhla byla moc těžká a dveře se zavřely.'],
      ['Vzít jen nejcennější', D, 1, 'Nejcennější kusy jsou v batohu a dveře jsou otevřené.', 'Vybírání trvalo dlouho a dveře se zavírají.'],
      ['Proklouznout s truhlou', O, 2, '{hrdina} proklouzl{a} s truhlou dveřmi v poslední chvíli.', 'Dveře přiskříply batoh a část pokladu zůstala uvnitř.'],
      ['Uctít ducha vládce', C, 0, 'Dveře se nezavřely. Snad duch vládce přijal úctu.', 'Ticho hrobky odpovědělo zavřením dveří.']),
  ],
};
