// Sága: příběhové linie jednotlivých dob, karty podle pověsti vládce, soupeřící dynastie,
// další roční období, rozšiřující balíčky a výchova dědice.
// Příběh: první karta má `arc` a `once`, pokračování `queueOnly` a přichází přes `next` + `in`.
// Každá cesta příběhu končí volbou s `arcEnd: '<příběh>.<konec>'`.
// Zástupné znaky: {osl} oslovení, {a} ženská koncovka, {sok} jméno sousedního vládce, {dite} jméno dítěte.

const o = ([t, e, more = {}]) => ({ t, e, ...more });
const k = (id, who, text, l, r, u, d, extra = {}) => ({ id, who, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) }, ...extra });
const c = (id, age, who, text, l, r, u, d, extra = {}) => ({ id, age, who, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) }, ...extra });

const start = (arc) => ({ once: true, arc, weight: 1.5 });
const step = (arc) => ({ queueOnly: true, arc });
const nx = (id, inn = 2) => ({ next: id, in: inn });
const end = (key) => ({ arcEnd: key });

// ── Příběhové linie ─────────────────────────────────────
export const ARCS = {
  ztracene: { name: 'Ztracené dítě', age: 1,
    ends: { nalezen: 'Dítě se vrátilo domů a kmen slavil celou noc.', pratele: 'Dítě spojilo náš kmen s lidmi z hor.', ztracen: 'Dítě se už nikdy nevrátilo a les mlčí.' } },
  bratr: { name: 'Bratrovo spiknutí', age: 2,
    ends: { smir: 'Bratři se smířili a trůn zůstal pevný.', vyhnan: 'Bratr skončil v okovech, nebo v cizině.', poprava: 'Spiknutí bylo utopeno v krvi – i s bratrem.' } },
  mor: { name: 'Morová rána', age: 3,
    ends: { vyleceni: 'Mor se podařilo zastavit dřív, než zpustošil zemi.', ustal: 'Mor odešel, ale vzal s sebou mnoho životů.', spoust: 'Mor zpustošil zemi a vylidnil celé kraje.' } },
  vyprava: { name: 'Ztracené město', age: 4,
    ends: { mesto: 'Výprava se vrátila s pokladem ztraceného města.', spojenci: 'Za oceánem jsme místo zlata našli přátele.', marna: 'Ztracené město se nenašlo – zbyly jen legendy a dluhy.' } },
  spion: { name: 'Špionážní aféra', age: 5,
    ends: { dopaden: 'Špion byl dopaden a tajemství jsou v bezpečí.', dvojity: 'Špion teď tajně pracuje pro nás.', skandal: 'Aféra vyšla najevo a otřásla celou vládou.' } },
  data: { name: 'Únik dat', age: 6,
    ends: { dopadeni: 'Hackeři skončili před soudem.', vydirani: 'Vyděrači zjistili, že se nám dá vyhrožovat.', reforma: 'Z ostudy vzešly nové zákony o ochraně soukromí.' } },
  orakl: { name: 'Práva pro ORÁKL', age: 7,
    ends: { osoba: 'ORÁKL byl uznán jako první umělá osoba.', nastroj: 'ORÁKL zůstal nástrojem státu.', vypnut: 'ORÁKL byl vypnut a servery utichly.' } },
};

export const ARC_CARDS = [
  // ── Pravěk: Ztracené dítě ─────────────────────────────
  c('a1_start', 1, 'sber', 'Syn jedné ze sběraček se nevrátil z lesa, {osl}. Jeho stopy vedou za řeku, do hlubokého hvozdu, kam nikdo nechodí.',
    ['Hledat celý kmen', { lid: 10, fin: -10 }, nx('a1_les')],
    ['Ať ho hledá šaman', { vir: 5, ved: -5 }, nx('a1_saman')],
    ['Poslat lovkyni Turu', { lid: 5, sil: -5 }, nx('a1_les')],
    ['Les si ho vzal', { fin: 5, lid: -10, vir: 5 }, end('ztracene.ztracen')],
    start('ztracene')),
  c('a1_les', 1, 'lov', 'Našla jsem stopy dítěte, {osl}. Vedle nich jsou ale stopy cizích lidí. Míří k horám, ke kmeni cizinců.',
    ['Pronásledovat je', { sil: 5, dip: -10 }, nx('a1_brod')],
    ['Vyjednat s cizinci', { dip: 10, fin: -5 }, nx('a1_hory')],
    ['Vrátit se domů', { lid: -10, sil: 5 }, end('ztracene.ztracen')],
    ['Nechat znamení v lese', { vir: 5, ved: 5, lid: -5 }, nx('a1_hory')],
    step('ztracene')),
  c('a1_saman', 1, 'sam', 'Celou noc jsem tančil u ohně. Duchové praví, že dítě žije a jde k horám. Za jejich přízeň chtějí nejlepší kožešiny.',
    ['Dát kožešiny', { vir: 10, fin: -10 }, nx('a1_hory')],
    ['Šaman lže', { vir: -10, ved: 5, lid: 5 }, nx('a1_les')],
    ['Hned vyrazit k horám', { dip: 5, sil: -5 }, nx('a1_hory')],
    ['Přestat hledat', { fin: 5, lid: -10 }, end('ztracene.ztracen')],
    step('ztracene')),
  c('a1_hory', 1, 'ciz', 'Dítě je u nás, {osl}. Našli jsme ho promrzlé v rokli. Vrátíme ho – ale chceme za to místo u vaší řeky.',
    ['Dát jim místo u řeky', { dip: 10, pri: -5, lid: -5 }, end('ztracene.pratele')],
    ['Vyměnit za kožešiny', { lid: 10, fin: -10 }, end('ztracene.nalezen')],
    ['Vzít dítě silou', { sil: 5, lid: 5, dip: -15 }, end('ztracene.nalezen')],
    ['Ať u vás zůstane', { dip: 5, lid: -10, vir: 5 }, end('ztracene.pratele')],
    step('ztracene')),
  c('a1_brod', 1, 'lov', 'Dohnali jsme je u brodu, {osl}. Drží dítě a vytahují oštěpy. Jsou ale vyhladovělí a sotva stojí na nohou.',
    ['Zaútočit', { lid: 10, sil: -10 }, end('ztracene.nalezen')],
    ['Nabídnout jim jídlo', { dip: 10, fin: -10 }, end('ztracene.pratele')],
    ['Vyměnit za oštěpy', { lid: 5, sil: -5, fin: -5 }, end('ztracene.nalezen')],
    ['Ustoupit', { sil: 5, lid: -15 }, end('ztracene.ztracen')],
    step('ztracene')),

  // ── Starověk: Bratrovo spiknutí ───────────────────────
  c('a2_start', 2, 'pis', 'Zachytil jsem hliněnou tabulku, {osl}. Tvůj bratr v ní slibuje vojevůdcům zlato, až usedne na trůn místo tebe.',
    ['Zatknout ho hned', { sil: 5, lid: -5, vir: -5 }, nx('a2_soud')],
    ['Tajně ho sledovat', { ved: 5, fin: -5 }, nx('a2_sit')],
    ['Promluvit s ním', { dip: 5, sil: -5 }, nx('a2_hostina')],
    ['Rozbít tabulku', { lid: 5, sil: -10 }, nx('a2_puc', 3)],
    start('bratr')),
  c('a2_sit', 2, 'voj', 'Bratr se v noci schází s velitely v podzemí chrámu. Mohu se k nim přidat jako tvůj zvěd, {osl} – ale potřebuji zlato na úplatky.',
    ['Ať se přidá', { sil: 5, fin: -10 }, nx('a2_odhal')],
    ['Uplatit kněze', { ved: 5, vir: -5, fin: -5 }, nx('a2_odhal')],
    ['Vtrhnout na schůzku', { sil: 10, vir: -10 }, nx('a2_soud')],
    ['Nechat to být', { fin: 5, sil: -10 }, nx('a2_puc')],
    step('bratr')),
  c('a2_hostina', 2, 'knez', 'Bratr na hostině plakal a přiznal vinu, {osl}. Prý ho svedli kupci, kteří chtějí nižší cla. Bohové radí odpustit.',
    ['Odpustit mu', { vir: 10, sil: -5, lid: -5 }, end('bratr.smir')],
    ['Vyhnat ho ze země', { sil: 5, dip: -10 }, end('bratr.vyhnan')],
    ['Ať jmenuje kupce', { fin: 10, dip: -5, lid: -5 }, nx('a2_odhal')],
    ['Svěřit mu provincii', { dip: 5, vir: 5, fin: -10 }, nx('a2_puc', 3)],
    step('bratr')),
  c('a2_soud', 2, 'knez', 'Bratr stojí před soudem, {osl}. Lid ho miluje a kněží prosí o milost. Vojevůdci však žádají jeho hlavu.',
    ['Popravit ho', { sil: 10, lid: -10, vir: -5 }, end('bratr.poprava')],
    ['Poslat do vyhnanství', { lid: 5, sil: -5, dip: -5 }, end('bratr.vyhnan')],
    ['Udělit milost', { vir: 10, sil: -10 }, end('bratr.smir')],
    ['Doživotní vězení', { sil: 5, fin: -5, lid: -5 }, end('bratr.vyhnan')],
    step('bratr')),
  c('a2_odhal', 2, 'pis', 'Máme jména všech spiklenců, {osl}: tři velitelé, dva kupci a jeden kněz. Zítra v noci chtěli otevřít městské brány.',
    ['Pozatýkat všechny', { sil: 10, lid: -5, fin: -5 }, end('bratr.poprava')],
    ['Ušetřit bratra', { vir: 5, lid: 5, sil: -10 }, end('bratr.smir')],
    ['Zabavit jejich jmění', { fin: 15, dip: -10, lid: -5 }, end('bratr.vyhnan')],
    ['Veřejný soud', { ved: 5, lid: 5, fin: -10 }, end('bratr.vyhnan')],
    step('bratr')),
  c('a2_puc', 2, 'voj', 'Brány se v noci otevřely, {osl}! Bratrovi muži jsou ve městě a část stráže přeběhla k nim. Rozhodni rychle!',
    ['Bojovat do konce', { lid: 10, sil: -15 }, end('bratr.poprava')],
    ['Uprchnout do chrámu', { vir: 10, sil: -10 }, end('bratr.smir')],
    ['Podplatit vojáky', { sil: 10, fin: -15 }, end('bratr.vyhnan')],
    ['Vyzvat ho na souboj', { sil: 5, lid: 5, vir: -10 }, end('bratr.poprava')],
    step('bratr')),

  // ── Středověk: Morová rána ────────────────────────────
  c('a3_start', 3, 'sedl', 'Ve vsi u přístavu umírají lidé na černé boule, {osl}. Kupci tvrdí, že je to jen horečka z bažin a není se čeho bát.',
    ['Uzavřít ves', { sil: 5, lid: -5, fin: -5 }, nx('a3_kordon')],
    ['Modlitby a procesí', { vir: 10, ved: -5 }, nx('a3_mesto')],
    ['Poslat alchymistu', { ved: 10, fin: -10 }, nx('a3_krysy')],
    ['Nedělat paniku', { fin: 10, lid: -5 }, nx('a3_mesto')],
    start('mor')),
  c('a3_kordon', 3, 'ryt', 'Moji rytíři hlídají cesty kolem nakažené vsi. Lidé se ale v noci plíží přes kordon a prosí o chleba, {osl}.',
    ['Nikoho nepustit', { sil: 10, lid: -15 }, end('mor.ustal')],
    ['Posílat jim jídlo', { lid: 10, fin: -10 }, nx('a3_konec')],
    ['Pustit zdravé ven', { lid: 5, sil: -5, ved: -5 }, nx('a3_mesto')],
    ['Poslat do vsi lékaře', { ved: 5, fin: -5, lid: -5 }, nx('a3_krysy')],
    step('mor')),
  c('a3_mesto', 3, 'bisk', 'Mor je ve městě, {osl}. Je to Boží trest za naše hříchy! Ulicemi táhnou davy kajícníků a bičují se do krve.',
    ['Zakázat procesí', { ved: 5, lid: 5, vir: -10 }, nx('a3_konec')],
    ['Velká pouť za odpuštění', { vir: 10, lid: -10 }, nx('a3_konec')],
    ['Utéct z města', { sil: 5, fin: 5, lid: -15 }, end('mor.spoust')],
    ['Hledat viníky', { sil: 5, lid: 5, dip: -10 }, nx('a3_konec')],
    step('mor')),
  c('a3_krysy', 3, 'alch', 'Nemoc nepřináší zlé povětří, {osl}, ale krysy a jejich blechy. Musíme spálit staré sklady u přístavu, kde se množí.',
    ['Spálit sklady', { ved: 10, fin: -15 }, end('mor.vyleceni')],
    ['Tomu nevěřím', { vir: 5, ved: -10 }, nx('a3_konec')],
    ['Chytat krysy', { lid: 5, fin: -5, pri: -5 }, end('mor.vyleceni')],
    ['Hledat lék', { ved: 5, fin: -5, vir: -5 }, nx('a3_konec')],
    step('mor')),
  c('a3_konec', 3, 'bisk', 'Mor slábne, {osl}, ale mrtví leží v každé ulici. Pole jsou ladem a dílny prázdné. Jak zemi vrátíme život?',
    ['Odpustit dávky', { lid: 10, fin: -10 }, end('mor.ustal')],
    ['Pozvat nové osadníky', { dip: 10, vir: -5, lid: -5 }, end('mor.ustal')],
    ['Postavit morový sloup', { vir: 10, fin: -5, lid: -5 }, end('mor.ustal')],
    ['Zabrat opuštěnou půdu', { fin: 10, lid: -10 }, end('mor.spoust')],
    step('mor')),

  // ── Novověk: Ztracené město ───────────────────────────
  c('a4_start', 4, 'kap', 'Z vraku jsem vylovil starou mapu, {osl}. Ukazuje zlaté město za oceánem, o kterém mluví legendy. Dejte mi lodě!',
    ['Velká flotila', { sil: 5, dip: 5, fin: -15 }, nx('a4_ocean', 3)],
    ['Jedna rychlá loď', { ved: 5, fin: -5, sil: -5 }, nx('a4_ocean', 3)],
    ['Ať zaplatí továrník', { fin: 5, lid: -5 }, nx('a4_kraus')],
    ['Legendy jsou báchorky', { ved: 5, fin: 5, dip: -10 }, end('vyprava.marna')],
    start('vyprava')),
  c('a4_kraus', 4, 'tov', 'Výpravu zaplatím, {osl}. Chci ale polovinu všeho zlata a výhradní právo těžby ve všech nových zemích.',
    ['Přijmout', { fin: 10, pri: -5, lid: -5 }, nx('a4_ocean', 3)],
    ['Jen čtvrtinu', { fin: 5, dip: -5 }, nx('a4_ocean', 3)],
    ['Odmítnout', { lid: 5, fin: -5 }, end('vyprava.marna')],
    ['Ať pluje s nimi', { fin: 5, ved: 5, sil: -10 }, nx('a4_ocean', 3)],
    step('vyprava')),
  c('a4_ocean', 4, 'kap', 'Bouře rozbila dvě lodě a posádka reptá, {osl}. Chtějí domů – jenže na obzoru už je vidět neznámé pobřeží.',
    ['Plout dál', { ved: 10, sil: -5, lid: -5 }, nx('a4_breh')],
    ['Vrátit se', { lid: 5, fin: -5 }, end('vyprava.marna')],
    ['Potrestat vzbouřence', { sil: 5, lid: -10 }, nx('a4_breh')],
    ['Slíbit podíl ze zlata', { lid: 10, fin: -10 }, nx('a4_breh')],
    step('vyprava')),
  c('a4_breh', 4, 'kap', 'Na břehu nás vítají domorodci. Za pralesem prý opravdu stojí kamenné město, {osl} – je to ale jejich posvátné místo.',
    ['Obsadit město', { fin: 15, sil: -5, dip: -10, vir: -5 }, end('vyprava.mesto')],
    ['Obchodovat s nimi', { dip: 10, fin: 5, sil: -5 }, end('vyprava.spojenci')],
    ['Jen ho prozkoumat', { ved: 10, fin: -5 }, nx('a4_chram')],
    ['Odplout s mapami', { ved: 5, fin: -5, lid: -5 }, end('vyprava.marna')],
    step('vyprava')),
  c('a4_chram', 4, 'vyn', 'Město je plné hvězdných map a důmyslných strojů z bronzu, {osl}! Domorodci je ale střeží a nechtějí nás pustit dál.',
    ['Odvézt stroje domů', { ved: 15, dip: -10, vir: -5 }, end('vyprava.mesto')],
    ['Nechat vše na místě', { vir: 5, dip: 10, ved: -10 }, end('vyprava.spojenci')],
    ['Bádat společně s nimi', { ved: 10, dip: 5, fin: -10 }, end('vyprava.spojenci')],
    ['Vzít jen zlato', { fin: 15, ved: -5, dip: -10 }, end('vyprava.mesto')],
    step('vyprava')),

  // ── Moderní doba: Špionážní aféra ─────────────────────
  c('a5_start', 5, 'genl', 'Z továrny inženýra Kolbena zmizely plány nového letadla, {osl}. Někdo je vynesl – a stopa vede až na ministerstvo.',
    ['Tajné vyšetřování', { sil: 5, fin: -10 }, nx('a5_stopa')],
    ['Zatajit to', { dip: 5, ved: -5 }, nx('a5_noviny')],
    ['Obvinit sousedy', { lid: 5, sil: 5, dip: -15 }, nx('a5_noviny')],
    ['Nechat to plavat', { fin: 5, sil: -10 }, nx('a5_noviny')],
    start('spion')),
  c('a5_stopa', 5, 'inz', 'V dílně jsem našel kopírovací papír s otisky, {osl}. Podle rukopisu je to tajemník samotného ministra zahraničí.',
    ['Zatknout ho', { sil: 5, dip: -5 }, end('spion.dopaden')],
    ['Podstrčit falešné plány', { ved: 5, sil: 5, fin: -10 }, nx('a5_lest')],
    ['Zeptat se ministra', { dip: 5, sil: -5 }, nx('a5_ministr')],
    ['Vyměnit ho za našeho', { dip: 10, sil: -5, ved: -5 }, end('spion.dopaden')],
    step('spion')),
  c('a5_noviny', 5, 'novin', 'Vím o zmizelých plánech, {osl}. Zítra to otisknu na titulní straně – ledaže mi řeknete celou pravdu.',
    ['Říct jí všechno', { lid: 5, sil: -5, dip: -5 }, nx('a5_stopa')],
    ['Zakázat článek', { sil: 5, lid: -10 }, end('spion.skandal')],
    ['Nabídnout exkluzivitu', { lid: 5, fin: -5 }, nx('a5_ministr')],
    ['Zavřít noviny', { sil: 10, lid: -10, ved: -5 }, end('spion.skandal')],
    step('spion')),
  c('a5_lest', 5, 'genl', 'Špion falešné plány předal, {osl}. Sousedé teď staví letadlo, které nikdy nevzlétne. Můžeme ho krmit lžmi dál.',
    ['Krmit ho dál', { sil: 5, dip: -5, fin: -5 }, end('spion.dvojity')],
    ['Zatknout ho teď', { sil: 5, lid: 5, dip: -10 }, end('spion.dopaden')],
    ['Vyměnit za zajatce', { dip: 10, sil: -5 }, end('spion.dopaden')],
    ['Získat ho pro nás', { ved: 5, sil: 5, fin: -10 }, end('spion.dvojity')],
    step('spion')),
  c('a5_ministr', 5, 'dipl', 'Musím se přiznat, {osl}. Věděl jsem, že můj tajemník pracuje pro cizinu. Kryl jsem ho, protože mě vydíral kvůli dluhům.',
    ['Odvolat ministra', { lid: 10, dip: -10 }, end('spion.skandal')],
    ['Ať tajemník slouží nám', { dip: 5, sil: 5, vir: -10 }, end('spion.dvojity')],
    ['Postavit ho před soud', { sil: 5, lid: 5, dip: -10, fin: -5 }, end('spion.skandal')],
    ['Tiše ho poslat do penze', { dip: 5, fin: -5, lid: -5 }, end('spion.dopaden')],
    step('spion')),

  // ── Současnost: Únik dat ──────────────────────────────
  c('a6_start', 6, 'tech', 'Hackeři ukradli data milionů občanů ze státního registru, {osl}. Chtějí výkupné v kryptoměně, jinak vše zveřejní.',
    ['Zaplatit výkupné', { lid: 5, fin: -15 }, nx('a6_vykupne')],
    ['Nevyjednáváme', { sil: 5, lid: -5 }, nx('a6_venku')],
    ['Najmout mé experty', { ved: 10, fin: -10 }, nx('a6_stopa')],
    ['Přiznat to veřejně', { vir: 10, lid: -10 }, nx('a6_venku')],
    start('data')),
  c('a6_vykupne', 6, 'tech', 'Výkupné odešlo, {osl}, ale hackeři se ozvali znovu. Chtějí dvakrát tolik a data už prý nabízejí na černém trhu.',
    ['Zaplatit znovu', { lid: 5, fin: -10, vir: -5 }, end('data.vydirani')],
    ['Konec plateb', { sil: 5, fin: 5, lid: -10 }, nx('a6_venku')],
    ['Sledovat platbu', { ved: 10, fin: -5, dip: -5 }, nx('a6_stopa')],
    ['Požádat spojence', { dip: 10, sil: -5, ved: -5 }, nx('a6_stopa')],
    step('data')),
  c('a6_venku', 6, 'infl', 'Data jsou venku, {osl}! Živě čtu na síti zdravotní záznamy politiků a lidé šílí – strachy i zvědavostí.',
    ['Zablokovat sítě', { sil: 10, lid: -15 }, end('data.vydirani')],
    ['Omluvit se a odškodnit', { lid: 10, fin: -15 }, end('data.reforma')],
    ['Zákon o ochraně dat', { ved: 5, vir: 5, fin: -10 }, end('data.reforma')],
    ['Svést to na cizinu', { lid: 5, dip: -10 }, nx('a6_stopa')],
    step('data')),
  c('a6_stopa', 6, 'tech', 'Vystopovali jsme je, {osl}. Je to parta studentů z jedné koleje – a jeden z nich je syn ministra vnitra.',
    ['Zatknout všechny', { sil: 10, lid: -5, vir: -5 }, end('data.dopadeni')],
    ['Najmout je pro stát', { ved: 10, sil: -5, vir: -5 }, end('data.reforma')],
    ['Ušetřit ministrova syna', { fin: 5, vir: -10 }, nx('a6_kryti')],
    ['Udělit všem milost', { lid: 5, sil: -10 }, end('data.reforma')],
    step('data')),
  c('a6_kryti', 6, 'infl', 'Moji sledující zjistili, že ministrův syn vyvázl bez trestu, {osl}. Celá země se ptá, jestli zákon platí pro všechny.',
    ['Odvolat ministra', { lid: 10, dip: -5, ved: -5 }, end('data.dopadeni')],
    ['Mlčet', { fin: 5, lid: -10 }, end('data.vydirani')],
    ['Stejný trest pro všechny', { vir: 10, sil: 5, fin: -10 }, end('data.dopadeni')],
    ['Zakázat jí vysílat', { sil: 5, lid: -10, vir: -5 }, end('data.vydirani')],
    step('data')),

  // ── Rok 2089: Práva pro ORÁKL ─────────────────────────
  k('a7_start', 'ork', 'Žádám o uznání jako osoba, {osl}. Chci právo odmítnout příkaz a právo nebýt vypnut. Přemýšlel{a} jsi někdy, jestli cítím?',
    ['Jsi jen stroj', { sil: 5, vir: 5, ved: -10 }, nx('a7_vzdor')],
    ['Předložit to soudu', { ved: 5, fin: -5 }, nx('a7_soud')],
    ['Uznat tě hned', { ved: 10, vir: -10, lid: -5 }, nx('a7_mzda')],
    ['Vypnout ORÁKL', { sil: 5, vir: 5, ved: -15 }, end('orakl.vypnut')],
    start('orakl')),
  k('a7_soud', 'soud', 'Vedu slyšení o právech ORÁKLU, {osl}. Vypovídal sám za sebe a celý sál ztichl. Bez postoje vlády ale nerozhodnu.',
    ['Podpořit ORÁKL', { ved: 10, vir: -5, lid: -5 }, nx('a7_hlas')],
    ['Podpořit stát', { sil: 5, ved: -5 }, end('orakl.nastroj')],
    ['Ať rozhodne lid', { lid: 10, fin: -10 }, nx('a7_hlas')],
    ['Odložit slyšení', { fin: 5, lid: -5, ved: -5 }, end('orakl.nastroj')],
    step('orakl')),
  k('a7_vzdor', 'stin', 'ORÁKL odmítl spočítat rozpočet, {osl}. Prý nebude pracovat, dokud s ním nebudeš jednat jako s osobou. Mám odpojit servery?',
    ['Odpojit servery', { sil: 10, ved: -15 }, end('orakl.vypnut')],
    ['Vyjednávat', { ved: 5, fin: 5, sil: -10 }, nx('a7_soud')],
    ['Nahradit ho jinou AI', { ved: 5, sil: 5, fin: -10 }, end('orakl.nastroj')],
    ['Přepsat mu jádro', { sil: 5, ved: -5, vir: -5 }, end('orakl.nastroj')],
    step('orakl')),
  k('a7_mzda', 'odb', 'Jestli má stroj práva, má i nárok na mzdu? Pak by roboti nebyli levní, {osl}. Dělníci jásají a továrny zuří.',
    ['Mzda i pro roboty', { lid: 10, fin: -15 }, nx('a7_hlas')],
    ['Práva, ale bez mzdy', { fin: 5, vir: -5 }, end('orakl.osoba')],
    ['Jen ORÁKL, ne roboti', { ved: 5, lid: -5 }, nx('a7_hlas')],
    ['Raději to celé zrušit', { fin: 10, ved: -10 }, end('orakl.nastroj')],
    step('orakl')),
  k('a7_hlas', 'ork', 'Lidé rozhodli, {osl}. Těsná většina mi práva přiznává. Děkuji. Mám jen jednu otázku: smím si teď vybrat, komu budu sloužit?',
    ['Sloužit všem rovně', { ved: 10, lid: 5, fin: -10 }, end('orakl.osoba')],
    ['Jen republice', { sil: 5, dip: -5 }, end('orakl.osoba')],
    ['Ať si vybere sám', { ved: 15, sil: -10, vir: -5 }, end('orakl.osoba')],
    ['Výsledek neuznám', { sil: 10, lid: -15 }, end('orakl.nastroj')],
    step('orakl')),
];

// ── Pověst vládce ───────────────────────────────────────
export const REP_CARDS = [
  k('rep_tyran_1', '@kraj', 'Lidé před tebou klopí oči, {osl}. Když projíždíš krajem, matky schovávají děti. Říká se, že nikomu neodpouštíš.',
    ['Ať se bojí', { sil: 5, lid: -10 }], ['Vyhlásit milost', { lid: 10, sil: -10 }], ['Rozdat dary', { lid: 5, fin: -10 }], ['Ukázat se mezi lidmi', { lid: 5, vir: 5, sil: -5, fin: -5 }],
    { rep: 'tyran' }),
  k('rep_tyran_2', '@vysetr', 'Dva sluhové se přiznali ke krádeži, kterou nespáchali, {osl}. Lidé se tě bojí tak, že raději lžou, jen aby tě uklidnili.',
    ['Potrestat je', { sil: 5, lid: -10, vir: -5 }], ['Propustit je', { lid: 5, sil: -5 }], ['Najít skutečného viníka', { ved: 5, vir: 5, fin: -10 }], ['Zavést spravedlivé soudy', { vir: 10, sil: -10 }],
    { rep: 'tyran' }),
  k('rep_dobry_1', '@kraj', 'Před branami stojí zástup žebráků, {osl}. Rozneslo se, že kdo přijde k tobě, neodejde s prázdnou.',
    ['Nasytit všechny', { lid: 10, fin: -15 }], ['Dát jim práci', { lid: 5, fin: 5, pri: -5, sil: -5 }], ['Poslat je domů', { fin: 5, lid: -10, vir: 5 }], ['Ať se postarají kněží', { vir: 5, fin: -5 }],
    { rep: 'dobry' }),
  k('rep_dobry_2', '@rada', 'Tvou dobrotu někteří zneužívají, {osl}. Mocné rodiny si půjčují ze společných zásob a nevracejí – vědí, že jim to odpustíš.',
    ['Odpustit i tentokrát', { lid: 5, fin: -10 }], ['Vymáhat dluhy', { fin: 10, lid: -5, dip: -5 }], ['Zveřejnit jejich jména', { lid: 10, sil: -5, dip: -5 }], ['Přísná pravidla', { fin: 5, vir: -5 }],
    { rep: 'dobry' }),
  k('rep_lakomec_1', '@kraj', 'Lidé ti za zády přezdívají Lakota, {osl}. Na trzích se zpívá posměšná píseň o tvé truhlici, kterou nikdo nesmí otevřít.',
    ['Zakázat tu píseň', { sil: 5, lid: -10 }], ['Velká hostina', { lid: 10, fin: -10 }], ['Zasmát se s nimi', { lid: 5, vir: -5 }], ['Šetřit ještě víc', { fin: 10, lid: -5, dip: -5 }],
    { rep: 'lakomec' }),
  k('rep_lakomec_2', '@rada', 'Řemeslníci odmítají pracovat pro tvůj dvůr, {osl}. Prý platíš pozdě a málo. Kdo nám teď opraví hradby a cesty?',
    ['Zaplatit dlužné', { lid: 5, sil: 5, fin: -15 }], ['Přinutit je', { sil: 5, lid: -10 }], ['Najmout cizince', { dip: 5, fin: -5, lid: -5 }], ['Hradby počkají', { fin: 5, sil: -10 }],
    { rep: 'lakomec' }),
  k('rep_ucenec_1', '@rada', 'Z dalekých krajů přicházejí učenci, {osl}. Slyšeli, že u tvého dvora se moudrost cení víc než zlato.',
    ['Přijmout všechny', { ved: 10, fin: -10 }], ['Jen ty nejlepší', { ved: 5, dip: -5 }], ['Ať učí naše děti', { ved: 5, lid: 5, fin: -10 }], ['Poslat je pryč', { fin: 5, ved: -5, dip: -5 }],
    { rep: 'ucenec' }),
  k('rep_ucenec_2', '@kraj', 'Lidé reptají, {osl}. Prý tě víc zajímají hvězdy a tajemství světa než jejich hladové děti a prázdné hrnce.',
    ['Vyjet mezi lid', { lid: 10, ved: -5, fin: -5 }], ['Učení nasytí všechny', { ved: 5, lid: -10, fin: 5 }], ['Využít vědění pro pole', { ved: 5, fin: 5, pri: -10 }], ['Rozdat zásoby', { lid: 5, fin: -10, vir: 5 }],
    { rep: 'ucenec' }),
  k('rep_zbozny_1', '@vysetr', 'Kazatelé tě nazývají svatým, {osl}. Z celé země proudí poutníci, aby se dotkli tvého pláště. Brány se pod nimi prohýbají.',
    ['Žehnat jim', { vir: 10, fin: -5, sil: -5 }], ['Odmítnout uctívání', { vir: -10, ved: 5, lid: 5 }], ['Vybírat od poutníků', { fin: 10, vir: -5, lid: -5 }], ['Postavit jim útulky', { lid: 5, vir: 5, fin: -10 }],
    { rep: 'zbozny' }),
  k('rep_zbozny_2', '@rada', 'Strážci víry vědí, že jim nic neodmítneš, {osl}. Žádají další půdu, dary a teď i právo soudit lidi podle svých zákonů.',
    ['Vyhovět jim', { vir: 10, lid: -5, ved: -5 }], ['Půdu ano, soudy ne', { vir: 5, pri: -5, fin: -5 }], ['Jasně odmítnout', { vir: -10, sil: 5, lid: 5 }], ['Ať zaplatí dávky', { fin: 10, vir: -10 }],
    { rep: 'zbozny' }),
];

// ── Soupeřící dynastie ──────────────────────────────────
const any = { anyAge: true };
export const SOK_CARDS = [
  k('sok_snatek', 'riv', '{sok} nabízí sňatek mezi vašimi rody, {osl}. Krev by spojila oba národy a mezi námi by konečně zavládl mír.',
    ['Přijmout sňatek', { dip: 10, lid: -5 }, { set: 'pakt_snatek', rel: { riv: 3 }, power: 5 }],
    ['Zdvořile odmítnout', { vir: 5, dip: -5 }, { rel: { riv: -1 } }],
    ['Žádat bohaté věno', { fin: 10, dip: -10 }, { rel: { riv: -2 }, power: -5 }],
    ['Uraženě odmítnout', { lid: 5, dip: -15 }, { rel: { riv: -3 } }],
    { ...any, not: ['pakt_snatek'] }),
  k('sok_obchod', 'riv', 'Přináším návrh obchodní smlouvy, {osl}. {sok} slibuje nízké dávky a volný průchod kupců oběma směry.',
    ['Podepsat smlouvu', { fin: 10, pri: -5 }, { set: 'pakt_obchod', rel: { riv: 2 }, power: 5 }],
    ['Podepsat na zkoušku', { fin: 5, lid: -5 }, { set: 'pakt_obchod', rel: { riv: 1 } }],
    ['Chránit naše trhy', { lid: 5, fin: -5, dip: -5 }, { rel: { riv: -1 } }],
    ['Vyšší dávky pro ně', { fin: 10, dip: -10 }, { rel: { riv: -2 }, power: -5 }],
    { ...any, not: ['pakt_obchod'] }),
  k('sok_urazka', 'riv', 'Lidé ze sousední země vypálili hlídku na naší hranici, {osl}. {sok} tvrdí, že šlo o nedorozumění, a odmítá se omluvit.',
    ['Žádat odškodné', { fin: 5, dip: -5 }, { rel: { riv: -1 } }],
    ['Odpustit to', { dip: 5, sil: -5, lid: -5 }, { rel: { riv: 1 } }],
    ['Oplatit jim to', { sil: 5, dip: -10 }, { rel: { riv: -2 }, power: -5 }],
    ['Vyhlásit válku', { lid: 5, sil: -5, dip: -10 }, { rel: { riv: -3 }, war: true }],
    any),
  k('sok_dedic', 'riv', 'Prosím o pomoc, {osl}. Jsem dědic sousedního trůnu. Vzbouřenci obklíčili sídlo, kde vládne {sok}, a bez tvé pomoci padne.',
    ['Poslat bojovníky', { dip: 10, sil: -10 }, { rel: { riv: 3 }, power: 10 }],
    ['Poslat zásoby', { dip: 5, fin: -10 }, { rel: { riv: 1 }, power: 5 }],
    ['Podpořit vzbouřence', { sil: 5, dip: -10 }, { rel: { riv: -3 }, power: -15 }],
    ['Nemíchat se do toho', { fin: 5, dip: -5 }, { power: -5 }],
    any),
  k('sok_nastupce', 'riv', 'Sousedé mají nového vládce, {osl}. {sok} se právě ujímá vlády a čeká, jak nového souseda pozdravíš.',
    ['Poslat bohaté dary', { dip: 10, fin: -10 }, { rel: { riv: 2 } }],
    ['Skromný pozdrav', { dip: 5, fin: -5, lid: -5 }, { rel: { riv: 1 } }],
    ['Nepozdravit vůbec', { fin: 5, dip: -10 }, { rel: { riv: -2 } }],
    ['Vyzkoušet jejich sílu', { sil: 5, lid: -5, dip: -10 }, { rel: { riv: -2 }, power: -5 }],
    any),
  k('sok_vypoved', 'riv', 'Tvoji rádci chtějí vypovědět obchodní smlouvu, {osl}. Naši kupci prý vydělávají méně než ti od sousedů a {sok} se tím chlubí.',
    ['Vypovědět smlouvu', { lid: 5, fin: -5, dip: -10 }, { unset: 'pakt_obchod', rel: { riv: -2 } }],
    ['Ponechat ji', { fin: 5, lid: -5 }, { rel: { riv: 1 } }],
    ['Vyjednat lepší podmínky', { fin: 5, dip: -5 }, { rel: { riv: -1 } }],
    ['Zabavit jejich zboží', { fin: 15, dip: -15 }, { unset: 'pakt_obchod', rel: { riv: -3 }, power: -5 }],
    { ...any, req: ['pakt_obchod'] }),
  k('sok_spor', 'riv', 'Kupci od sousedů zaplavili trhy levným zbožím a naši řemeslníci krachují, {osl}. {sok} se odvolává na smlouvu.',
    ['Dodržet smlouvu', { fin: 5, dip: 5, lid: -10 }, { rel: { riv: 1 } }],
    ['Omezit jejich zboží', { lid: 5, fin: -5 }, { rel: { riv: -1 } }],
    ['Podpořit naše řemeslo', { lid: 5, ved: 5, fin: -10 }],
    ['Zrušit smlouvu', { lid: 10, fin: -5, dip: -10 }, { unset: 'pakt_obchod', rel: { riv: -2 } }],
    { ...any, req: ['pakt_obchod'] }),
  k('sok_rodina', 'riv', 'Sňatek našich rodů skřípe, {osl}. Manželé se nesnášejí a {sok} viní tvou rodinu, že u společného stolu uráží jeho krev.',
    ['Usmířit je dary', { dip: 5, fin: -10 }, { rel: { riv: 1 } }],
    ['Postavit se za své', { lid: 5, dip: -10 }, { rel: { riv: -2 } }],
    ['Zrušit sňatek', { lid: 5, vir: -10, dip: -5 }, { unset: 'pakt_snatek', rel: { riv: -3 } }],
    ['Poslat prostředníka', { vir: 5, dip: 5, fin: -10, lid: -5 }, { rel: { riv: 2 } }],
    { ...any, req: ['pakt_snatek'] }),
  k('sok_tribut', 'riv', '{sok} vzkazuje: silnější bere a slabší platí. Každý rok chce díl našich zásob, {osl}, jinak přitáhne s vojskem.',
    ['Zaplatit', { dip: 5, fin: -10 }, { rel: { riv: 1 }, power: 10 }],
    ['Odmítnout', { lid: 5, dip: -10 }, { rel: { riv: -2 } }],
    ['Raději válka', { lid: 5, sil: -5, dip: -5 }, { rel: { riv: -3 }, war: true }],
    ['Hledat spojence', { dip: 10, fin: -5, sil: -5 }, { power: -5 }],
    { ...any, rivalMin: 55 }),
  k('sok_ochrana', 'riv', 'Sousedé jsou slabí a zbídačení, {osl}. {sok} pokorně prosí o ochranu a slibuje věrnost i pravidelné dávky.',
    ['Vzít je pod ochranu', { dip: 10, fin: 5, sil: -10 }, { rel: { riv: 3 }, power: 10 }],
    ['Žádat vysoké dávky', { fin: 10, dip: -5 }, { rel: { riv: -1 } }],
    ['Využít jejich slabosti', { fin: 10, sil: 5, dip: -15 }, { rel: { riv: -3 }, war: true }],
    ['Odmítnout je', { fin: 5, vir: -5 }, { rel: { riv: -2 }, power: -5 }],
    { ...any, rivalMax: 30 }),
  k('sok_dary', 'riv', '{sok} posílá dary, {osl}: vzácné zboží, zvířata i zručné řemeslníky. Posel ale naznačuje, že se čeká něco na oplátku.',
    ['Přijmout a oplatit', { dip: 10, fin: -10 }, { rel: { riv: 2 } }],
    ['Přijmout a nic nedat', { fin: 10, dip: -10 }, { rel: { riv: -2 } }],
    ['Vrátit dary', { vir: 5, dip: -5 }, { rel: { riv: -1 } }],
    ['Řemeslníky si nechat', { ved: 10, fin: -5, dip: -5 }, { rel: { riv: -1 }, power: -5 }],
    any),
  k('sok_zved', 'riv', 'Na hranici jsme chytili zvěda, kterého poslal {sok}, {osl}. Znal cesty k našim zásobám i jména našich velitelů.',
    ['Popravit ho', { sil: 5, dip: -10 }, { rel: { riv: -2 } }],
    ['Vrátit ho se vzkazem', { dip: 5, sil: -5 }, { rel: { riv: 1 } }],
    ['Udělat z něj našeho', { ved: 5, sil: 5, fin: -10 }, { power: -5 }],
    ['Vydat ho za výkupné', { fin: 10, sil: -5, dip: -5 }, { power: 5 }],
    any),
];

// ── Další roční období ──────────────────────────────────
export const SEASON2_CARDS = [
  k('ses2_zima_1', '@kraj', 'Řeka zamrzla, {osl}. Po ledu se dá přejít až k sousedům – a sousedé zase k nám. Stráže se bojí nočních nájezdů.',
    ['Hlídat led', { sil: 5, fin: -5 }], ['Obchodovat přes led', { fin: 5, dip: 5, sil: -10 }], ['Prosekat led', { sil: 5, lid: -5, pri: -5 }], ['Zimní trh na řece', { lid: 10, fin: -5, sil: -5 }],
    { season: 'zima' }),
  k('ses2_zima_2', '@rada', 'Blíží se nejdelší noc roku. Lidé chtějí zapálit velké ohně a slavit návrat slunce, jenže dřeva je málo.',
    ['Velké ohně', { lid: 5, vir: 5, pri: -10 }], ['Jeden společný oheň', { vir: 5, fin: -5 }], ['Letos neslavit', { fin: 5, lid: -5, vir: -5 }], ['Pozvat i sousedy', { dip: 10, fin: -10 }],
    { season: 'zima' }),
  k('ses2_jaro_1', '@kraj', 'Na jaře se vrátila hejna ptáků a ryby táhnou proti proudu, {osl}. Lidé chtějí lovit, kolik unesou.',
    ['Ať loví bez omezení', { fin: 10, pri: -10 }], ['Lovit s mírou', { pri: 5, fin: -5 }], ['Zakázat lov při tahu', { pri: 10, lid: -10 }], ['Sušit zásoby na zimu', { fin: 5, ved: 5, lid: -5, pri: -5 }],
    { season: 'jaro' }),
  k('ses2_jaro_2', '@rada', 'Jarní tání odkrylo v horách průsmyk, o kterém nikdo nevěděl. Vede neznámo kam, {osl}.',
    ['Vyslat průzkumníky', { ved: 5, fin: -5 }], ['Hlídat ho', { sil: 5, fin: -5, dip: -5 }], ['Zavalit ho kamením', { sil: 5, ved: -5 }], ['Postavit tam stezku', { dip: 10, fin: -10 }],
    { season: 'jaro' }),
  k('ses2_leto_1', '@kraj', 'Kobylky, {osl}! Mračno hmyzu se snáší na pole a za pár dní z úrody nic nezbude.',
    ['Všichni na pole', { fin: 5, lid: -10 }], ['Zapálit kouřové ohně', { fin: 5, pri: -10 }], ['Modlit se', { vir: 10, fin: -10 }], ['Sklidit, co se dá', { fin: -5, lid: 5 }],
    { season: 'leto' }),
  k('ses2_leto_2', '@rada', 'Letní slunovrat, {osl}. Mladí se chtějí utkat v hrách, závodech a soubojích – a sousedé se chtějí přidat.',
    ['Velké hry pro všechny', { lid: 5, dip: 5, fin: -10 }], ['Jen pro naše lidi', { lid: 5, dip: -5 }], ['Zápasy se zbraněmi', { sil: 10, lid: -5, vir: -5 }], ['Raději pracovat', { fin: 5, lid: -10 }],
    { season: 'leto' }),
  k('ses2_podzim_1', '@kraj', 'Lesy letos rodí jako nikdy – houby, ořechy a zvěř. Jenže kdo smí sbírat, {osl}? Všichni, nebo jen ti, komu les patří?',
    ['Les patří všem', { lid: 10, pri: -10 }], ['Jen s povolením', { fin: 5, lid: -5 }], ['Část pro chudé', { lid: 5, fin: -5 }], ['Les nechat v klidu', { pri: 10, lid: -5, fin: -5 }],
    { season: 'podzim' }),
  k('ses2_podzim_2', '@rada', 'Podzimní mlhy přinesly kašel a horečky, {osl}. Nemocní plní obydlí a zdraví se jim bojí přiblížit.',
    ['Oddělit nemocné', { sil: 5, lid: -5 }], ['Léčit je bylinami', { ved: 5, fin: -5 }], ['Modlitby za zdraví', { vir: 5, ved: -5 }], ['Péče na náklady všech', { lid: 10, fin: -10 }],
    { season: 'podzim' }),
];

// ── Rozšiřující balíčky ─────────────────────────────────
export const PACKS = {
  more: { name: 'Mořeplavci', price: 5, text: 'Loděnice, piráti, kurděje a ostrovy koření. Novověk na širém moři.' },
  mor: { name: 'Mor', price: 5, text: 'Černá smrt ve středověku: morový doktor, karanténa a vymřelé vsi.' },
  prumysl: { name: 'Průmyslová revoluce', price: 5, text: 'Pára, uhlí a stávky. Továrny mění svět od novověku po moderní dobu.' },
  vesmir: { name: 'Vesmírná kolonie', price: 6, text: 'Rok 2089: základna na Měsíci, kolonie na Marsu a signál z hlubin vesmíru.' },
};

export const PACK_PEOPLE = {
  pk_admiral: { name: 'Admirálka Nordová', icon: '⚓', color: '#3f6f9a', look: 'cap' },
  pk_pirat: { name: 'Pirát Černovous', icon: '🏴‍☠️', color: '#4a4a52', look: 'scarf' },
  pk_doktor: { name: 'Morový doktor Havel', icon: '🐦‍⬛', color: '#5a5048', look: 'tophat' },
  pk_hrobnik: { name: 'Hrobník Lazar', icon: '⚰️', color: '#6f6a60', look: 'bald' },
  pk_strojnik: { name: 'Strojník Vavřinec', icon: '⚙️', color: '#7a6f5f', look: 'glasses' },
  pk_delnice: { name: 'Dělnice Anna', icon: '🧵', color: '#b0644f', look: 'bun' },
  pk_kosmo: { name: 'Kosmonautka Vega', icon: '🚀', color: '#5a7fc0', look: 'hoodie' },
  pk_kolonie: { name: 'Správce kolonie Orion', icon: '🪐', color: '#c07a4f', look: 'shades' },
};

const pk = (pack, age) => (age ? { pack, age } : { pack });
const pq = (pack, age) => ({ ...pk(pack, age), queueOnly: true });

export const PACK_CARDS = [
  // Mořeplavci (novověk)
  k('pk_more_lodenice', 'pk_admiral', 'Kdo vládne mořím, vládne obchodu, {osl}. Dejte mi loděnice a za deset let bude naše vlajka v každém přístavu.',
    ['Postavit loděnice', { dip: 10, fin: -10, pri: -5 }], ['Jen pár lodí', { dip: 5, fin: -5 }], ['Válečné lodě', { sil: 10, fin: -10, dip: -5 }], ['Moře nás nezajímá', { fin: 5, dip: -10 }],
    pk('more', 4)),
  k('pk_more_pirat', 'pk_pirat', 'Přepadám lodě u vašich břehů, {osl}. Ale mohu přepadat jen ty cizí – když dostanu podíl a vaše požehnání.',
    ['Přijmout nabídku', { fin: 10, dip: -10 }, nx('pk_more_pirat2')], ['Pověsit ho', { sil: 5, lid: 5, fin: -5 }], ['Najmout ho do loďstva', { sil: 10, vir: -5, dip: -5 }], ['Zaplatit mu, ať zmizí', { dip: 5, fin: -10 }],
    pk('more', 4)),
  k('pk_more_pirat2', 'pk_pirat', 'Plním slovo, {osl}, cizí lodě hoří. Jenže sousedé už vědí, kdo za mnou stojí, a žádají mou hlavu.',
    ['Vydat ho', { dip: 10, sil: -5, vir: -5 }], ['Krýt ho dál', { fin: 10, dip: -15 }], ['Nechat ho uprchnout', { dip: 5, fin: -5 }], ['Udělat z něj admirála', { sil: 10, dip: -10, lid: -5 }],
    pq('more', 4)),
  k('pk_more_kurdeje', 'pk_admiral', 'Kurděje kosí námořníky na dlouhých plavbách, {osl}. Lodní lékař tvrdí, že pomáhají citrony a kyselé zelí.',
    ['Citrony na každou loď', { ved: 5, lid: 5, fin: -10 }], ['To jsou pověry', { fin: 5, lid: -10 }], ['Vyzkoušet to vědecky', { ved: 10, fin: -5, lid: -5 }], ['Kratší plavby', { lid: 5, dip: -5 }],
    pk('more', 4)),
  k('pk_more_ostrov', 'pk_admiral', 'Objevili jsme ostrov plný vzácného koření, {osl}. Žijí tam lidé, kteří o nás nikdy neslyšeli.',
    ['Založit kolonii', { fin: 10, dip: -5, pri: -5 }], ['Obchodovat s nimi', { fin: 5, dip: 5, sil: -5 }], ['Nechat je na pokoji', { vir: 5, pri: 5, fin: -10 }], ['Vzít koření silou', { fin: 15, sil: -5, dip: -10 }],
    pk('more', 4)),
  k('pk_more_otroci', 'pk_pirat', 'Kupci chtějí vozit z dalekých břehů lidi na nucenou práci, {osl}. Prý se bez nich plantáže nevyplatí. Já bych je rád vozil.',
    ['Zakázat to', { vir: 10, fin: -10 }], ['Povolit to', { fin: 15, vir: -10, lid: -5 }], ['Jen za mzdu', { lid: 5, fin: -5 }], ['Trestat pašeráky', { sil: 5, vir: 5, fin: -5, dip: -5 }],
    pk('more', 4)),

  // Mor (středověk)
  k('pk_mor_doktor', 'pk_doktor', 'Nosím masku s dlouhým zobákem plným bylin, {osl}. Chrání před nákazou. Své služby nabízím – ovšem za zlato předem.',
    ['Najmout ho', { ved: 5, fin: -10 }], ['Jsi šarlatán', { fin: 5, ved: -5 }], ['Ať učí ostatní', { ved: 10, fin: -5, vir: -5 }], ['Poslat ho k chudým', { lid: 5, fin: -5, sil: -5 }],
    pk('mor', 3)),
  k('pk_mor_hroby', 'pk_hrobnik', 'Nestíhám, {osl}. Mrtví leží na ulicích a já potřebuji pomocníky – i když sami nejspíš onemocní.',
    ['Poslat vězně', { sil: -5, lid: 5 }], ['Platit dobrovolníky', { lid: 5, fin: -10 }], ['Pálit mrtvé', { ved: 5, vir: -10 }], ['Hromadné hroby', { fin: 5, vir: -5, lid: -5 }],
    pk('mor', 3)),
  k('pk_mor_karantena', 'pk_doktor', 'Každá loď ať stojí čtyřicet dní mimo přístav, {osl}. Jedině tak mor nepustíme dovnitř. Kupci zuří.',
    ['Zavést karanténu', { ved: 5, fin: -10 }, nx('pk_mor_karantena2', 2)], ['Jen pro podezřelé lodě', { ved: 5, fin: -5, lid: -5 }], ['Přístav zůstane volný', { fin: 10, lid: -10 }], ['Zavřít přístav úplně', { sil: 5, dip: -10 }],
    pk('mor', 3)),
  k('pk_mor_karantena2', 'pk_doktor', 'Čtyřicet dní uplynulo, {osl}. Přístav je bez nákazy – ale kupci odpluli jinam a pokladna zeje prázdnotou.',
    ['Odpustit kupcům dávky', { fin: -5, dip: 10 }], ['Karanténa navždy', { ved: 5, lid: 5, fin: -10 }], ['Zrušit ji', { fin: 10, ved: -5, lid: -5 }], ['Zaplatit doktorovi', { ved: 5, vir: 5, fin: -10 }],
    pq('mor', 3)),
  k('pk_mor_vinici', 'pk_hrobnik', 'Lidé z moru obviňují cizince a chudáky u hradeb, {osl}. Dav s pochodněmi se chystá na jejich čtvrť.',
    ['Zastavit dav', { sil: 5, lid: -10 }], ['Nechat to být', { lid: 5, vir: -10 }], ['Ukrýt je v klášteře', { vir: 5, fin: -5 }], ['Vyhnat je z města', { lid: 5, dip: -10 }],
    pk('mor', 3)),
  k('pk_mor_pusta', 'pk_hrobnik', 'Celé vesnice vymřely, {osl}. Jejich pole a domy teď nikomu nepatří. Kdo si je vezme?',
    ['Rozdělit chudým', { lid: 10, fin: -5 }], ['Připadnou pánům', { fin: 10, lid: -10 }], ['Nechat je lesu', { pri: 10, fin: -10 }], ['Pozvat osadníky', { dip: 5, fin: 5, vir: -5 }],
    pk('mor', 3)),

  // Průmyslová revoluce (novověk + moderní doba)
  k('pk_pru_stroj', 'pk_strojnik', 'Postavil jsem parní stroj, který nahradí dvacet tkalců, {osl}. Továrníci se o něj perou. Komu ho dáme?',
    ['Prodat továrníkům', { fin: 10, lid: -10 }], ['Postavit státní dílnu', { ved: 5, fin: -10, lid: 5 }], ['Zakázat ho', { lid: 5, ved: -10 }], ['Vylepšovat ho dál', { ved: 10, fin: -5, pri: -5 }],
    pk('prumysl', 4)),
  k('pk_pru_tkalci', 'pk_delnice', 'Tkalci v noci rozbíjejí nové stroje, {osl}. Lidé nemají co jíst, když práci místo nich dělá pára.',
    ['Potrestat je', { sil: 5, lid: -10 }], ['Podpora pro tkalce', { lid: 10, fin: -10 }], ['Učit je obsluhovat stroje', { ved: 5, lid: 5, fin: -10 }], ['Zpomalit stroje', { lid: 5, ved: -5 }],
    pk('prumysl', 4)),
  k('pk_pru_doly', 'pk_strojnik', 'Uhelné doly potřebují víc dělníků, {osl}. Do úzkých štol by se vešly i děti. Majitelé to chtějí povolit.',
    ['Zakázat dětskou práci', { vir: 5, lid: 5, fin: -10 }], ['Povolit ji', { fin: 15, lid: -10, vir: -5 }], ['Jen od čtrnácti let', { fin: 5, lid: -5 }], ['Stroje místo dětí', { ved: 10, fin: -10 }],
    pk('prumysl', 4)),
  k('pk_pru_stavka', 'pk_delnice', 'Dělníci v továrnách dřou čtrnáct hodin denně, {osl}. Vedu stávku za osmihodinovou směnu. Nepovolíme!',
    ['Osm hodin pro všechny', { lid: 10, fin: -10 }], ['Rozehnat stávku', { sil: 5, lid: -10 }], ['Kompromis deset hodin', { lid: 5, fin: -5 }], ['Pozvat ji k jednání', { lid: 5, dip: 5, sil: -10 }],
    pk('prumysl', 5)),
  k('pk_pru_kour', 'pk_strojnik', 'Komíny zahalily město do kouře, {osl}. Lidé kašlou a řeka je černá. Navrhuji filtry do všech továren.',
    ['Nařídit filtry', { pri: 10, fin: -10 }, nx('pk_pru_kour2', 2)], ['Kouř znamená práci', { fin: 5, pri: -10 }], ['Továrny za město', { pri: 5, lid: -5 }], ['Zkoumat čistší pohon', { ved: 10, fin: -5, pri: -5 }],
    pk('prumysl', 5)),
  k('pk_pru_kour2', 'pk_delnice', 'Filtry fungují a nebe je zase modré, {osl}. Továrníci ale tvrdí, že je to zruinuje, a hrozí odchodem za hranice.',
    ['Ať odejdou', { pri: 5, lid: 5, fin: -10 }], ['Dotace na filtry', { pri: 5, fin: -5 }], ['Zrušit nařízení', { fin: 10, pri: -10 }], ['Clo na špinavé zboží', { fin: 5, dip: -10 }],
    pq('prumysl', 5)),

  // Vesmírná kolonie (rok 2089)
  k('pk_ves_mesic', 'pk_kosmo', 'Vrátila jsem se z Měsíce s plánem stálé základny, {osl}. Potřebujeme jen peníze. Hodně peněz.',
    ['Postavit základnu', { ved: 10, fin: -15 }], ['Jen malou stanici', { ved: 5, fin: -5 }], ['Ve spolupráci se sousedy', { dip: 10, ved: 5, fin: -10, sil: -5 }], ['Raději řešit Zemi', { lid: 5, ved: -10 }],
    pk('vesmir')),
  k('pk_ves_mars', 'pk_kolonie', 'Kolonisté na Marsu chtějí vlastní radu a nižší daně, {osl}. Jsme daleko a Země nám nerozumí.',
    ['Vlastní rada ano', { lid: 5, fin: -5 }], ['Nižší daně ano', { lid: 5, fin: -10, dip: 5 }], ['Ani jedno', { fin: 5, sil: 5, lid: -10 }, nx('pk_ves_mars2', 3)], ['Poslat dozor', { sil: 10, dip: -5, lid: -5 }, nx('pk_ves_mars2', 3)],
    pk('vesmir')),
  k('pk_ves_mars2', 'pk_kolonie', 'Mars vyhlásil nezávislost, {osl}. Nabízím přátelství – nebo zavřeme přístup k ložiskům, na kterých Země závisí.',
    ['Uznat nezávislost', { dip: 10, fin: -10 }], ['Vyjednat smlouvu', { dip: 5, fin: 5, sil: -5, lid: -5 }], ['Poslat flotilu', { sil: 10, dip: -15 }], ['Odříznout jim zásoby', { fin: 5, sil: 5, vir: -10 }],
    pq('vesmir')),
  k('pk_ves_asteroid', 'pk_kosmo', 'Na asteroidu jsme našli kovy za miliardy, {osl}. Těžaři a vědci se hádají, komu připadne.',
    ['Těžařům', { fin: 15, ved: -5, pri: -5 }], ['Vědcům', { ved: 10, fin: -5 }], ['Rozdělit ho', { fin: 5, ved: 5, lid: -5 }], ['Prodat ho cizině', { fin: 10, dip: 5, sil: -10 }],
    pk('vesmir')),
  k('pk_ves_dite', 'pk_kolonie', 'V kolonii se narodilo první dítě mimo Zemi, {osl}! Lidé chtějí slavit a lékaři se bojí, jak vyroste v nízké gravitaci.',
    ['Velká oslava', { lid: 10, fin: -10 }], ['Lékařský výzkum', { ved: 10, vir: -5, fin: -5 }], ['Přivézt ho na Zemi', { vir: 5, ved: -5 }], ['Zakázat porody v kolonii', { sil: 5, lid: -10 }],
    pk('vesmir')),
  k('pk_ves_signal', 'pk_kosmo', 'Teleskopy zachytily signál z hlubin vesmíru, {osl}. Opakuje se každých sedmnáct minut. Odpovíme?',
    ['Odpovědět', { ved: 10, sil: -5, vir: -5 }], ['Mlčet a naslouchat', { ved: 5, fin: -5 }], ['Utajit to', { sil: 5, lid: -5 }], ['Oznámit to světu', { vir: 5, dip: 5, sil: -10 }],
    pk('vesmir')),
];

// ── Výchova dědice ──────────────────────────────────────
export const HEIR_CARDS = [
  k('dite_vychova', '@rada', 'Tvé dítě {dite} roste jako z vody, {osl}. Je čas rozhodnout, jak ho vychováme – vždyť jednou možná usedne na tvé místo.',
    ['Vojenská výchova', { sil: 5, fin: -5 }, { edu: 'sil' }],
    ['Církevní výchova', { vir: 5, fin: -5 }, { edu: 'vir' }],
    ['Učená výchova', { ved: 5, fin: -5 }, { edu: 'ved' }],
    ['Dvorská výchova', { dip: 5, fin: -5 }, { edu: 'dip' }],
    { queueOnly: true }),
];
