// Další karty dávných dob – nové situace, aby se karty v jedné době tolik neopakovaly.
// Osm karet pro každou dobu 1–6, postavy z AGE_PEOPLE příslušné doby.

const o = ([t, e, more = {}]) => ({ t, e, ...more });
const c = (id, age, who, text, l, r, u, d, extra = {}) => ({ id, age, who, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) }, ...extra });

export const AGE_CARDS_MORE = [
  // ── Pravěk ────────────────────────────────────────────
  c('p2_povoden', 1, 'star', 'Řeka se v noci vylila z břehů a odnesla půlku tábora, {osl}. Kožešiny plavou mezi stromy a děti pláčou.',
    ['Přestěhovat se výš', { lid: 5, fin: -5, pri: 5 }], ['Lovit, co plave', { fin: 10, lid: -5, sil: -5 }], ['Postavit hráz z kamení', { ved: 5, sil: 5, pri: -5, lid: -5 }], ['Řeka se zlobí', { vir: 5, ved: -5, lid: 5 }]),
  c('p2_med', 1, 'sber', 'V duté lípě jsem našla včelí hnízdo plné medu! Jenže včely bodají a lípa je prý strom duchů.',
    ['Vykouřit včely', { fin: 10, pri: -5, vir: -5 }], ['Nechat lípu být', { vir: 5, pri: 5, fin: -5 }], ['Brát jen trochu', { fin: 5, pri: 5, sil: -5 }], ['Dát med dětem', { lid: 10, fin: -5 }]),
  c('p2_houby', 1, 'sam', 'Šaman snědl podivné houby a tři dny tancoval kolem ohně. Teď chce, aby je na slavnosti ochutnal celý kmen.',
    ['Ať tancuje sám', { vir: -5, lid: 5 }], ['Slavnost pro všechny', { vir: 10, lid: 5, sil: -10 }], ['Houby vyhodit', { vir: -10, lid: -5 }], ['Zkoumat, co dělají', { ved: 5, lid: -5, sil: 5 }]),
  c('p2_luk', 1, 'ciz', 'Cizinec ukazuje ohnutý prut s tětivou. Vystřelí z něj šíp dál, než kdokoli hodí oštěpem. Chce u vás zůstat.',
    ['Přijmout ho mezi nás', { dip: 10, ved: 5, lid: -5 }], ['Vyměnit luk za maso', { sil: 5, fin: -5 }], ['Poslat ho pryč', { dip: -10, lid: 5 }], ['Luky jen pro lovce', { sil: 5, pri: -5, dip: -5 }]),
  c('p2_medved', 1, 'lov', 'V nejsušší jeskyni u řeky přezimuje medvěd. Lovci ji chtějí pro kmen, starší radí ji nechat.',
    ['Vyhnat medvěda', { sil: -5, lid: 5, pri: -5 }], ['Najít jinou jeskyni', { pri: 5, fin: -5 }], ['Medvěd je posvátný', { vir: 5, pri: 5, lid: -5 }], ['Počkat do jara', { lid: -5, sil: 5 }]),
  c('p2_fletna', 1, 'sam', 'Ze stehenní kosti jsem vyřezal píšťalu. Když na ni hraju, duchové tančí. Lovci tvrdí, že plaší zvěř.',
    ['Hrát každý večer', { lid: 10, sil: -5, fin: -5 }], ['Hrát jen při obřadu', { vir: 5, lid: 5, sil: -5 }], ['Ať naučí děti', { ved: 5, lid: 5, vir: -5 }], ['Píšťalu zakázat', { sil: 5, lid: -10 }]),
  c('p2_sucho', 1, 'sber', 'Měsíc nezapršelo. Bobule usychají na keřích a tráva žloutne, {osl}. Stáda odcházejí na sever.',
    ['Jít za stády', { fin: 5, lid: -5, dip: -5 }], ['Kopat studnu', { ved: 5, fin: -5, sil: 5 }], ['Tanec pro déšť', { vir: 5, fin: -5 }], ['Požádat sousedy', { dip: 5, fin: 5, sil: -5, vir: -5 }]),
  c('p2_zavod', 1, 'lov', 'Dva mladí lovci se hádají, kdo z nich zabil jelena. Každý tvrdí, že jeho oštěp byl první. Málem se poprali.',
    ['Rozdělit jelena', { lid: 5, sil: -5 }], ['Ať závodí v běhu', { sil: 5, lid: 5, fin: -5 }], ['Jelen patří kmeni', { fin: 5, lid: -5, dip: 5 }], ['Zeptat se duchů', { vir: 5, ved: -5, lid: -5 }]),

  // ── Starověk ──────────────────────────────────────────
  c('s2_scitani', 2, 'pis', 'Chci sečíst všechny obyvatele říše, {osl}. Budeme vědět, kolik máme rukou k práci – a kolik daní vybrat.',
    ['Sečíst každého', { ved: 10, fin: 5, lid: -10 }], ['Lidé nejsou ovce', { lid: 5, ved: -5 }], ['Jen pro zásoby obilí', { fin: 5, ved: 5, vir: -5 }], ['Ať to dělají kněží', { vir: 5, ved: -5, fin: -5 }]),
  c('s2_slon', 2, 'kup', 'Z daleké země jsem přivezla dar od tamního krále – slona! Bohužel už sežral půlku palácové zahrady.',
    ['Slon do průvodu', { lid: 10, fin: -5, pri: -5 }], ['Poslat ho do chrámu', { vir: 5, fin: -5 }], ['Vrátit ho zdvořile', { dip: -5, fin: 5 }], ['Poslat dar zpátky', { dip: 10, fin: -5, vir: -5 }]),
  c('s2_zatmeni', 2, 'filo', 'Spočítal jsem, že za tři dny zmizí slunce za měsícem. Kněží o tom nevědí. Mám to ohlásit lidu?',
    ['Ohlásit to všem', { ved: 5, vir: -10, fin: 5 }], ['Říct jen kněžím', { vir: 5, dip: -5, ved: -5 }], ['Ohlásit to sám', { vir: 5, lid: 5, ved: -5, fin: -5 }], ['Ať mlčí', { lid: -5, sil: 5, ved: -5 }]),
  c('s2_zold', 2, 'voj', 'Vojáci už půl roku nedostali žold, {osl}. Postávají u bran a reptají. Dlouho je neudržím.',
    ['Zaplatit jim', { fin: -5, sil: 5, lid: -5 }], ['Dát jim půdu', { lid: -5, sil: 5, pri: -5 }], ['Propustit polovinu', { sil: -10, fin: 10 }], ['Slíbit kořist', { sil: 5, dip: -10, fin: 5 }]),
  c('s2_knihovna', 2, 'pis', 'Každá loď v přístavu má svitky. Kdybychom je opsali, měli bychom největší knihovnu světa.',
    ['Opisovat všechny', { ved: 10, fin: -5, dip: -5 }], ['Svitky zabavit', { ved: 5, dip: -10, fin: 5 }], ['Vyměňovat se', { dip: 5, ved: 5, fin: -5 }], ['Na co knihy?', { fin: 5, ved: -10, lid: 5 }]),
  c('s2_mince', 2, 'kup', 'Lidé pořád mění kozy za obilí a hádají se o cenu. Razme mince s tvou tváří – obchod poběží jako po vodě!',
    ['Razit mince', { fin: 10, dip: 5, lid: -5 }], ['Zůstat u výměny', { lid: 5, fin: -5 }], ['Mince s bohy', { vir: 5, fin: 5, lid: -5, dip: -5 }], ['Mince pro cizince', { dip: 10, fin: -5, sil: -5 }]),
  c('s2_kobylky', 2, 'knez', 'Z pouště přilétl mrak kobylek a sežral obilí na polích. Velekněz volá po velkém postu a modlitbách.',
    ['Půst a modlitby', { vir: 5, lid: -5, fin: -5 }], ['Otevřít sýpky', { lid: 5, fin: -5 }], ['Kobylky jíst', { fin: 5, vir: -10, lid: 5 }], ['Koupit obilí', { dip: 5, fin: -5, pri: 5 }]),
  c('s2_hlasovani', 2, 'filo', 'Moji žáci chtějí, aby o zákonech hlasovali všichni svobodní občané na náměstí. Ne jen ty, {osl}.',
    ['Shromáždění lidu', { lid: 10, sil: -10 }], ['Rada moudrých', { ved: 5, lid: 5, vir: -5 }], ['Vládne král', { sil: 5, lid: -10, vir: 5 }], ['Hlasovat o drobnostech', { lid: 5, fin: -5, sil: -5 }]),

  // ── Středověk ─────────────────────────────────────────
  c('m2_pytlak', 3, 'sedl', 'Sedláci chytili v panském lese zajíce, {osl}. Les je tvůj, ale děti mají hlad. Hajný žádá trest.',
    ['Odpustit jim', { lid: 10, sil: -5, pri: -5 }], ['Přísně potrestat', { sil: 5, lid: -10 }], ['Otevřít les na sběr', { lid: 5, pri: -5, fin: -5 }], ['Ať odpracují pokutu', { fin: 5, lid: -5, pri: 5 }]),
  c('m2_bylinkarka', 3, 'bisk', 'Ve vsi žije stará bylinkářka. Léčí lépe než lazebník, ale biskup tvrdí, že je to čarodějnice.',
    ['Nechat ji léčit', { ved: 5, lid: 5, vir: -10 }], ['Vyhnat ji ze vsi', { vir: 5, ved: -5, lid: -5 }], ['Ať učí v klášteře', { vir: 5, fin: -5, lid: 5 }], ['Rozsoudit to', { lid: 5, sil: -5, dip: 5 }]),
  c('m2_most', 3, 'sedl', 'Jarní velká voda strhla dřevěný most. Bez něj vozíme obilí na trh přes brod a půlku utopíme.',
    ['Kamenný most', { fin: -10, lid: 5, dip: 5 }], ['Spravit ten dřevěný', { fin: -5, pri: -5, lid: 5 }], ['Most s mýtem', { fin: 10, lid: -10 }], ['Ať ho postaví sedláci', { fin: 5, lid: -5, ved: -5 }]),
  c('m2_drak', 3, 'ryt', 'V jeskyni nad vsí prý žije drak, {osl}! Chci ho zabít a získat slávu. Sedláci ho viděli jen v mlze.',
    ['Ať jede na draka', { sil: -5, lid: 5, vir: 5 }], ['Draci neexistují', { ved: 5, vir: -5, lid: -5 }], ['Poslat učence', { ved: 5, fin: -5, sil: 5 }], ['Vybrat dračí daň', { fin: 10, lid: -10 }]),
  c('m2_bryle', 3, 'alch', 'Vybrousil jsem dvě skla do rámečku. Staří mniši s nimi znovu přečtou drobné písmo! Mám jich udělat víc?',
    ['Brýle pro mnichy', { vir: 5, fin: -5, lid: 5 }], ['Brýle na trh', { fin: 10, ved: 5, vir: -5 }], ['To je kouzlo', { vir: 5, ved: -10 }], ['Zkus i dalekohled', { ved: 5, fin: -5, sil: 5 }]),
  c('m2_odpustky', 3, 'bisk', 'Na dostavbu kostela nemáme, {osl}. Mohli bychom prodávat odpustky – kdo zaplatí, má hříchy odpuštěné.',
    ['Prodávat odpustky', { fin: 10, vir: -5, lid: -5 }], ['To je hřích', { vir: 5, fin: -5 }], ['Sbírka dobrovolná', { lid: 5, fin: 5, vir: -5, sil: -5 }], ['Ať zaplatí šlechta', { fin: 5, sil: -10, lid: 5 }]),
  c('m2_laska', 3, 'ryt', 'Zamiloval jsem se do dcery mlynáře a chci si ji vzít. Můj rod zuří a hrozí, že mě vydědí, {osl}.',
    ['Požehnat sňatku', { lid: 10, dip: -5, sil: -5 }], ['Rod má přednost', { sil: 5, lid: -5 }], ['Povýšit mlynáře', { lid: 5, fin: -10, dip: 5 }], ['Pošli ho na cesty', { dip: 5, fin: -5 }]),
  c('m2_kometa', 3, 'alch', 'Na nebi se objevila kometa s ohnivým ocasem. Lidé říkají, že ohlašuje konec světa, a nechodí na pole.',
    ['Vysvětlit lidem', { ved: 5, vir: -5, lid: 5 }], ['Procesí za spásu', { vir: 5, fin: -5, lid: -5 }], ['Poslat je na pole', { fin: 5, lid: -10, sil: 5 }], ['Zapsat ji do kronik', { ved: 5, fin: -5, dip: -5 }]),

  // ── Novověk ───────────────────────────────────────────
  c('n2_balon', 4, 'vyn', 'Ušila jsem obří balón z hedvábí a naplnila ho horkým vzduchem. Poletí s ním člověk nad celým městem!',
    ['Ať letí', { ved: 5, lid: 5, fin: -5 }], ['Nejdřív kachna a ovce', { lid: 5, fin: 5, pri: -5 }], ['Balón pro vojsko', { sil: 5, ved: 5, dip: -10 }], ['To je rouhání', { vir: 5, ved: -10 }]),
  c('n2_deti', 4, 'rev', 'V továrnách pracují osmileté děti čtrnáct hodin denně. Továrníci tvrdí, že jinak zkrachují.',
    ['Zakázat dětskou práci', { lid: 10, fin: -10 }], ['Povinná škola', { ved: 5, fin: -10, lid: 5 }], ['Jen kratší směny', { lid: 5, fin: -5 }], ['Ať rozhodne trh', { fin: 10, lid: -10, vir: -5 }]),
  c('n2_pirati', 4, 'kap', 'Piráti přepadli tři naše obchodní lodě, {osl}. Jejich kapitán nabízí, že nás nechá být – za poplatek.',
    ['Zaplatit piratům', { fin: -10, dip: 5 }], ['Poslat válečné lodě', { sil: -5, fin: -5, dip: 5, lid: 5 }], ['Najmout je pro nás', { fin: 5, sil: 5, dip: -10 }], ['Lodě v konvojích', { fin: -5, dip: 5, sil: -5 }]),
  c('n2_kavarny', 4, 'hrabe', 'Ve městě se otevírají kavárny. Lidé tam pijí černý nápoj a celé dny probírají politiku. Nebezpečné, ne?',
    ['Kavárny zavřít', { sil: 5, lid: -10, ved: -5 }], ['Daň z kávy', { fin: 10, lid: -5 }], ['Ať si povídají', { lid: 5, ved: 5, sil: -5 }], ['Poslat tam špehy', { sil: 5, ved: -5, lid: -5 }]),
  c('n2_brambory', 4, 'hrabe', 'Z Ameriky přišly brambory. Sedláci je nechtějí jíst, prý jsou jedovaté. Jak je přesvědčit, {osl}?',
    ['Nařídit pěstování', { fin: 5, lid: -10, sil: 5 }], ['Pole hlídat jako poklad', { lid: 5, fin: 5, sil: -5 }], ['Sníst je veřejně', { lid: 5, dip: 5 }], ['Nechat je prasatům', { pri: 5, fin: -5 }]),
  c('n2_hromosvod', 4, 'vyn', 'Kovová tyč na střeše svede blesk do země. Kněží říkají, že nikdo nemá právo bránit Božímu hněvu.',
    ['Na každou střechu', { ved: 5, vir: -10, fin: 5 }], ['Jen na sklady prachu', { sil: 5, fin: 5, lid: -5 }], ['I na kostelní věž', { ved: 5, vir: -5, lid: 5 }], ['Tyče zakázat', { vir: 5, ved: -10, lid: -5 }]),
  c('n2_clo', 4, 'tov', 'Z ciziny proudí levná látka a moje tkalcovny nestíhají. Uvalte na ni clo, nebo propustím dělníky!',
    ['Vysoké clo', { fin: 5, dip: -10, lid: 5 }], ['Volný obchod', { dip: 10, fin: -5, lid: -5 }], ['Nové stroje na dluh', { ved: 5, fin: -10, pri: -5 }], ['Ať se snaží sám', { fin: 5, lid: -5, sil: -5 }]),
  c('n2_kurdeje', 4, 'kap', 'Na dlouhých plavbách námořníkům krvácejí dásně a padají zuby. Lodní lékař přísahá na citróny.',
    ['Citróny na každou loď', { ved: 5, lid: 5, fin: -5 }], ['Kratší plavby', { fin: -5, dip: -5, lid: 5 }], ['Kysané zelí', { ved: 5, fin: 5, lid: -5 }], ['Námořníci vydrží', { fin: 5, lid: -10, sil: -5 }]),

  // ── Moderní doba ──────────────────────────────────────
  c('x2_letiste', 5, 'inz', 'Letadla už vozí cestující přes oceán. Postavíme velké letiště, {osl}? Musela by ustoupit jedna vesnice.',
    ['Postavit letiště', { fin: 5, dip: 10, pri: -10, lid: -5 }], ['Vesnice zůstane', { lid: 5, pri: 5, dip: -5 }], ['Menší letiště', { dip: 5, fin: 5, pri: -5 }], ['Letiště pro armádu', { sil: 5, fin: -5, lid: -5 }]),
  c('x2_olympiada', 5, 'dipl', 'Můžeme pořádat olympijské hry! Svět by se díval na nás. Jen stadiony stojí víc než celý rozpočet školství.',
    ['Pořádat hry', { dip: 10, lid: 5, fin: -10 }], ['Raději školy', { ved: 5, dip: -5 }], ['Skromné hry', { dip: 5, lid: 5, fin: -5, sil: -5 }], ['Bojkotovat je', { dip: -10, sil: 5, fin: 5 }]),
  c('x2_penicilin', 5, 'inz', 'Z plísně jsme získali lék, který zabíjí bakterie. Zachrání miliony. Výroba je ale drahá, {osl}.',
    ['Továrna na lék', { ved: 5, lid: 5, fin: -5 }], ['Nejdřív pro vojáky', { sil: 5, lid: -5, ved: 5 }], ['Prodat patent', { fin: 10, ved: -5, dip: -5 }], ['Sdílet se světem', { dip: 10, fin: -5, sil: -5 }]),
  c('x2_skandal', 5, 'novin', 'Mám důkazy, že ministr stavebnictví bral úplatky. Zítra to vyjde na titulní straně, {osl}.',
    ['Ministra odvolat', { lid: 10, sil: -5 }], ['Zastavit tisk', { sil: 5, lid: -15 }], ['Vyšetřovací komise', { lid: 5, fin: -5 }], ['Hájit ho', { lid: -5, fin: 5, dip: -5 }]),
  c('x2_vojna', 5, 'genl', 'Chci prodloužit vojenskou službu na tři roky. Mladí muži by z ní prý vyšli jako chlapi.',
    ['Tři roky', { sil: 10, lid: -10 }], ['Zkrátit ji', { lid: 10, sil: -10 }], ['Civilní služba', { lid: 5, sil: -5, pri: 5 }], ['Profesionální armáda', { sil: 5, fin: -5, lid: -5 }]),
  c('x2_swing', 5, 'novin', 'Mládež tančí po nocích divoký swing a nosí podivné účesy. Rodiče píšou do novin, že je to konec mravů.',
    ['Ať se baví', { lid: 10, vir: -10 }], ['Zakázat tančírny', { vir: 5, lid: -10 }], ['Swing v rozhlase', { lid: 5, fin: 5, vir: -5 }], ['Taneční kurzy', { lid: 5, fin: -5, dip: 5 }]),
  c('x2_povoden', 5, 'genl', 'Řeky se rozvodnily a zatopily půl země. Moji vojáci jsou připraveni. Mají stavět hráze, nebo hlídat hranice?',
    ['Všichni na hráze', { lid: 10, sil: -10 }], ['Hlídat hranice', { sil: 5, lid: -10 }], ['Požádat sousedy', { dip: 5, sil: -5, fin: 5 }], ['Nové přehrady', { pri: -5, fin: 5, ved: 5 }]),
  c('x2_azyl', 5, 'dipl', 'Slavný vědec utekl ze sousední diktatury a žádá o azyl. Sousedé hrozí, že zavřou hranice pro naše zboží.',
    ['Dát mu azyl', { ved: 5, dip: -10, lid: 5 }], ['Vydat ho zpět', { dip: 5, ved: -5, lid: -10 }], ['Poslat ho dál', { dip: 5, ved: -5 }], ['Azyl potají', { ved: 5, sil: -5, dip: -5, lid: 5 }]),

  // ── Současnost ────────────────────────────────────────
  c('c2_drony', 6, 'tech', 'Chci rozvážet balíky drony přímo do oken, {osl}. Nad městem by jich létaly tisíce. Stačí mi povolení.',
    ['Povolit drony', { fin: 10, lid: -5 }], ['Zakázat je', { lid: 5, ved: -5, fin: -5 }], ['Jen pro léky', { lid: 10, fin: -5 }], ['Drony pro policii', { sil: 5, lid: -5, fin: 5 }]),
  c('c2_vyzva', 6, 'infl', 'Po síti se šíří výzva: děti jedí kapsle pracího prášku na kameru. Prosím, udělejte něco, {osl}!',
    ['Kampaň s Kiki', { lid: 5, fin: -5 }], ['Zablokovat videa', { sil: 5, lid: -5 }], ['Výuka na školách', { ved: 5, fin: -5 }], ['Rodiče si poradí', { lid: -10, fin: 5 }]),
  c('c2_sucho', 6, 'klim', 'Třetí rok sucha, {osl}. Vody je málo – dostanou ji zemědělci, továrny, nebo golfová hřiště?',
    ['Zemědělci', { pri: 5, lid: 5, fin: -10 }], ['Továrny', { fin: 10, pri: -10 }], ['Zdražit vodu', { fin: 5, lid: -10, pri: 5 }], ['Zadržet vodu v krajině', { pri: 10, fin: -5, lid: 5 }]),
  c('c2_hackeri', 6, 'tech', 'Hackeři zašifrovali počítače v nemocnicích a chtějí výkupné v kryptoměně. Operace stojí.',
    ['Zaplatit výkupné', { fin: -10, lid: 5, sil: -5 }], ['Nikdy neplatit', { sil: 5, lid: -10 }], ['Najmout hackery', { ved: 5, fin: -5, sil: -5 }], ['Obvinit cizí stát', { dip: -10, sil: 5, lid: 5 }]),
  c('c2_volby16', 6, 'infl', 'Moji sledující chtějí volit už od šestnácti. Prý jim jde o budoucnost víc než dospělým. Co vy na to?',
    ['Volit od šestnácti', { lid: 10, vir: -5, sil: -5 }], ['Až v osmnácti', { vir: 5, lid: -5 }], ['Zkusit v obcích', { lid: 5, ved: 5, fin: -5 }], ['Raději občanku', { ved: 5, fin: -5 }]),
  c('c2_vlci', 6, 'klim', 'Do hor se po sto letech vrátili vlci. Ekologové jásají, ale pastevci přišli o ovce a chtějí je odstřelit.',
    ['Chránit vlky', { pri: 5, lid: -5, dip: 5 }], ['Povolit odstřel', { lid: 5, pri: -10 }], ['Ploty a psi', { fin: -5, pri: 5, lid: 5 }], ['Vlci jako atrakce', { fin: 10, pri: -5, vir: -5 }]),
  c('c2_tovarna', 6, 'tech', 'Postavím u vás obří továrnu na baterie. Tisíce míst! Chci jen daňové prázdniny a pole za městem.',
    ['Vítejte', { fin: 10, lid: 5, pri: -10 }], ['Bez úlev', { fin: 5, dip: -10 }], ['Jen na brownfieldu', { pri: 5, fin: 5, lid: -5 }], ['Ať jde jinam', { pri: 5, fin: -5, lid: -5 }]),
  c('c2_hadry', 6, 'infl', 'Moje videa s nákupy levného oblečení mají miliony zhlédnutí. Klimatoložky mi píšou, že hory hadrů končí na skládkách.',
    ['Daň na rychlou módu', { pri: 10, fin: 5, lid: -10 }], ['Do toho mi nic není', { fin: 5, pri: -10 }], ['Kampaň secondhand', { pri: 5, lid: 5, fin: -10 }], ['Kiki ať se omluví', { lid: -5, dip: 5, vir: -5 }]),
];
