// Hloubka hry: vzpoury frakcí, nejisté zvěsti a dlouhodobé ozvěny rozhodnutí.
// Postavy '@kraj', '@rada', '@vysetr' dosadí hra podle doby, proto jsou texty nadčasové.
// 'calm' uklidní frakci, 'next' + 'in' naplánuje eskalaci, 'later' naplánuje odložený následek.

const o = ([t, e, more = {}]) => ({ t, e, ...more });
const k = (id, who, text, l, r, u, d, extra = {}) => ({ id, who, text, opts: { left: o(l), right: o(r), up: o(u), down: o(d) }, ...extra });

// ── Vzpoury frakcí ─────────────────────────────────────
export const FACTION_CARDS = [
  // kněží a strážci víry
  k('vzp_kneze_1', '@rada', 'Kněží a strážci víry reptají, {osl}. Tvrdí, že jsi opustil{a} posvátné zvyky, a hrozí, že proti tobě obrátí lid.',
    ['Vyjednat s nimi', { fin: -10, vir: 5 }, { calm: 'kneze' }],
    ['Ignorovat je', { fin: 5, vir: -5 }, { next: 'vzp_kneze_2', in: 2 }],
    ['Zakázat jim kázat', { sil: 5, vir: -10, lid: -5 }, { next: 'vzp_kneze_2', in: 2 }],
    ['Postavit nový chrám', { vir: 10, fin: -10, ved: -5 }, { calm: 'kneze' }],
    { faction: 'kneze' }),
  k('vzp_kneze_2', '@vysetr', 'Kněží otevřeně vyzývají k neposlušnosti, {osl}. Věřící odmítají odvádět dávky a v chrámech se kuje spiknutí.',
    ['Pokořit se před nimi', { vir: 10, lid: -10, fin: -15 }, { calm: 'kneze' }],
    ['Zatknout vůdce', { vir: -15, sil: 5 }],
    ['Zabavit majetek chrámů', { vir: -10, fin: 10, lid: -5 }],
    ['Opřít se o učence', { vir: -10, ved: 10 }],
    { faction: 'kneze', generated: true }),

  // obchodníci
  k('vzp_kupci_1', '@rada', 'Obchodníci jsou nespokojení s dávkami, {osl}. Hrozí, že zavřou krámy a odvezou zboží za hranice.',
    ['Snížit jim dávky', { fin: -10, lid: -5 }, { calm: 'kupci' }],
    ['Ať si stěžují', { lid: 5, fin: -5 }, { next: 'vzp_kupci_2', in: 2 }],
    ['Pohrozit trestem', { sil: 5, fin: -5, dip: -5 }, { next: 'vzp_kupci_2', in: 2 }],
    ['Slíbit nové trhy', { dip: -5, fin: 5, pri: -5 }, { calm: 'kupci' }],
    { faction: 'kupci' }),
  k('vzp_kupci_2', '@vysetr', 'Obchodníci zavřeli trhy a skupují zásoby, {osl}. Ceny letí vzhůru a lid hladoví.',
    ['Přistoupit na vše', { fin: 5, lid: -15, sil: -10 }, { calm: 'kupci' }],
    ['Zabavit jejich sklady', { fin: -15, sil: 5, lid: 5 }],
    ['Pozvat cizí obchodníky', { fin: -10, dip: 10, lid: -5 }],
    ['Rozdělit zásoby lidu', { fin: -15, lid: 10 }],
    { faction: 'kupci', generated: true }),

  // válečníci
  k('vzp_vojsko_1', '@rada', 'Válečníci se bouří, {osl}. Říkají, že je zanedbáváš, a velitelé se scházejí bez tvého vědomí.',
    ['Zvýšit jim odměny', { fin: -10, sil: 5 }, { calm: 'vojsko' }],
    ['Nevšímat si toho', { fin: 5, sil: -5 }, { next: 'vzp_vojsko_2', in: 2 }],
    ['Propustit velitele', { sil: -10, lid: 5 }, { next: 'vzp_vojsko_2', in: 2 }],
    ['Slíbit jim tažení', { sil: 10, dip: -10 }, { calm: 'vojsko' }],
    { faction: 'vojsko' }),
  k('vzp_vojsko_2', '@vysetr', 'Válečníci obklíčili tvé sídlo, {osl}. Žádají moc, zbraně a hlavy tvých rádců.',
    ['Vydat jim, co chtějí', { sil: 10, lid: -15, dip: -10 }, { calm: 'vojsko' }],
    ['Vyzbrojit lid proti nim', { sil: -15, lid: 5, fin: -5 }],
    ['Uplatit část velitelů', { sil: -10, fin: -10 }],
    ['Prosit sousedy o pomoc', { sil: -10, dip: -5, fin: -5 }],
    { faction: 'vojsko', generated: true }),

  // učenci
  k('vzp_ucenci_1', '@rada', 'Učenci si stěžují, že jejich práce nikoho nezajímá, {osl}. Někteří už balí a chtějí odejít k sousedům.',
    ['Dát jim prostředky', { fin: -10, ved: 5 }, { calm: 'ucenci' }],
    ['Ať si jdou', { ved: -5, fin: 5 }, { next: 'vzp_ucenci_2', in: 2 }],
    ['Zakázat jim odchod', { sil: 5, ved: -5, dip: -5 }, { next: 'vzp_ucenci_2', in: 2 }],
    ['Vyslechnout jejich rady', { ved: 10, vir: -5, sil: -5 }, { calm: 'ucenci' }],
    { faction: 'ucenci' }),
  k('vzp_ucenci_2', '@vysetr', 'Učenci šíří spisy proti tvé vládě, {osl}. Mladí je poslouchají a staré pořádky se otřásají.',
    ['Dát jim místo v radě', { ved: 10, vir: -15, sil: -10 }, { calm: 'ucenci' }],
    ['Spálit jejich spisy', { ved: -15, vir: 5 }],
    ['Vyhnat je ze země', { ved: -10, dip: -5, lid: 5 }],
    ['Zavřít jejich školy', { ved: -10, fin: 5, lid: -5 }],
    { faction: 'ucenci', generated: true }),
];

// ── Nejisté zvěsti ─────────────────────────────────────
const rum = { rumor: true };
export const RUMOR_CARDS = [
  k('zvest_utok', '@vysetr', 'Zvědové hlásí, že se za hranicí shromažďuje cizí vojsko, {osl}. Nikdo ho ale na vlastní oči neviděl.',
    ['Zbrojit a opevnit', { fin: -10, sil: 5 }, { later: [{ p: 0.5, in: 2, e: { fin: 5 }, text: 'Poplach byl planý – část zbraní jsme alespoň prodali.' }] }],
    ['Nevěřit tomu', { fin: 5 }, { later: [{ p: 0.5, in: 2, e: { sil: -15, lid: -10 }, text: 'Zvěst se potvrdila: nepřítel opravdu zaútočil a zastihl nás nepřipravené.' }] }],
    ['Vyslat další zvědy', { ved: -5, fin: -5 }, { later: [{ p: 0.25, in: 2, e: { sil: -10 }, text: 'Zvědové se vrátili pozdě – nepřítel už překročil hranici.' }] }],
    ['Poslat k nim posla', { dip: 5, sil: -5 }, { later: [{ p: 0.5, in: 2, e: { dip: -10 }, text: 'Posel byl zajat. Sousedé nás teď mají za slabochy.' }] }],
    rum),
  k('zvest_mor', '@kraj', 'Šíří se zvěst, že v sousední osadě řádí nemoc, {osl}. Pocestní prý přinášejí nákazu.',
    ['Uzavřít cesty', { fin: -10, dip: -5 }, { later: [{ p: 0.5, in: 2, e: { lid: -5 }, text: 'Nemoc se neukázala – lidé reptají kvůli zbytečně zavřeným cestám.' }] }],
    ['Jsou to pověry', { lid: 5 }, { later: [{ p: 0.5, in: 2, e: { lid: -20 }, text: 'Zvěst se potvrdila: nemoc dorazila i k nám a mnozí zemřeli.' }] }],
    ['Ať to učenci prověří', { ved: -5, fin: -5 }, { later: [{ p: 0.25, in: 2, e: { lid: -10 }, text: 'Učenci nemoc podcenili. Nakazilo se několik rodin.' }] }],
    ['Modlit se za ochranu', { vir: 5, ved: -5 }, { later: [{ p: 0.5, in: 2, e: { lid: -15, vir: -5 }, text: 'Modlitby nepomohly – nemoc přišla a víra lidí se otřásla.' }] }],
    rum),
  k('zvest_zrada', '@vysetr', 'Posel tvrdí, že jeden z tvých rádců tajně jedná s cizinci, {osl}. Důkazy ale nemá.',
    ['Rádce odvolat', { dip: -5, lid: -5 }, { later: [{ p: 0.5, in: 2, e: { vir: -5, lid: -5 }, text: 'Ukázalo se, že rádce byl nevinný. Lidé tě mají za nespravedlivého vládce.' }] }],
    ['Nevěřit pomluvám', { dip: 5 }, { later: [{ p: 0.5, in: 2, e: { dip: -15, sil: -5 }, text: 'Zvěst se potvrdila: rádce vyzradil naše plány cizincům.' }] }],
    ['Dát ho sledovat', { fin: -5, ved: -5 }, { later: [{ p: 0.25, in: 2, e: { dip: -10 }, text: 'Rádce sledování odhalil a stihl uprchnout i s tajemstvími.' }] }],
    ['Zkoušet ho lží', { vir: -5 }, { later: [{ p: 0.5, in: 2, e: { sil: 5 }, text: 'Falešná zpráva se dostala k cizincům – zrádce se prozradil sám.' }] }],
    rum),
  k('zvest_poklad', '@kraj', 'Šíří se zvěst o pokladu ukrytém v horách, {osl}. Lidé chtějí opustit pole a jít ho hledat.',
    ['Vyslat výpravu', { fin: -10, lid: 5 }, { later: [{ p: 0.5, in: 2, e: { fin: 20 }, text: 'Výprava se vrátila s bohatstvím! Zvěst byla pravdivá.' }] }],
    ['Zakázat hledání', { lid: -5, fin: 5 }, { later: [{ p: 0.5, in: 2, e: { dip: -5, fin: -5 }, text: 'Poklad našli cizinci a odvezli si ho za hranice.' }] }],
    ['Ať hledá, kdo chce', { fin: -5, pri: -5 }, { later: [{ p: 0.5, in: 2, e: { lid: -10 }, text: 'Poklad byl jen pohádka – hledači zanedbali pole a teď hladoví.' }] }],
    ['Prověřit staré zápisy', { ved: -5 }, { later: [{ p: 0.25, in: 2, e: { fin: 15, ved: 5 }, text: 'Učenci v zápisech našli cestu k pokladu.' }] }],
    rum),
  k('zvest_sucho', '@rada', 'Staří lidé tvrdí, že znamení věstí suché léto, {osl}. Máme už teď šetřit zásoby?',
    ['Šetřit a skladovat', { lid: -10, fin: 5 }, { later: [{ p: 0.5, in: 3, e: { fin: 10, lid: 5 }, text: 'Sucho opravdu přišlo, ale díky zásobám nikdo nehladověl.' }] }],
    ['Žít jako dosud', { lid: 5 }, { later: [{ p: 0.5, in: 3, e: { fin: -15, lid: -10 }, text: 'Zvěst se potvrdila: sucho spálilo úrodu a zásoby nestačí.' }] }],
    ['Kopat nové studny', { fin: -10, pri: -5 }, { later: [{ p: 0.5, in: 3, e: { pri: 5 }, text: 'Léto bylo deštivé – studny alespoň zavlažily nová pole.' }] }],
    ['Obětovat za déšť', { vir: 5, fin: -5 }, { later: [{ p: 0.5, in: 3, e: { fin: -10, vir: -5 }, text: 'Sucho přišlo i přes oběti a lidé začali pochybovat.' }] }],
    rum),
  k('zvest_spojenec', '@vysetr', 'Posel tvrdí, že sousední vládce chce uzavřít spojenectví, ale bojí se to říct nahlas.',
    ['Poslat dary', { fin: -10, dip: 5 }, { later: [{ p: 0.5, in: 2, e: { dip: 10 }, text: 'Zvěst se potvrdila: soused dary přijal a spojenectví je na světě.' }] }],
    ['Je to past', { sil: 5, dip: -5 }, { later: [{ p: 0.5, in: 2, e: { dip: -15 }, text: 'Soused nabídku myslel vážně. Naše nedůvěra ho urazila.' }] }],
    ['Vyslat tajného posla', { fin: -5, ved: -5 }, { later: [{ p: 0.25, in: 2, e: { dip: -5, sil: -5 }, text: 'Tajného posla chytili a sousedé zuří.' }] }],
    ['Počkat, až se ozve', { dip: -5 }, { later: [{ p: 0.5, in: 2, e: { dip: -10, fin: -5 }, text: 'Soused se spojil s jinými. Na nás zbyly jen drobky.' }] }],
    rum),
  k('zvest_lupici', '@kraj', 'Šíří se zvěst, že v lesích se usadila tlupa lupičů, {osl}. Obchodníci se bojí cestovat.',
    ['Pročesat lesy', { sil: -5, pri: -5, fin: -5 }, { later: [{ p: 0.5, in: 2, e: { lid: -5 }, text: 'Poplach byl planý – výprava jen poplašila zvěř a unavila válečníky.' }] }],
    ['Nic se neděje', { fin: 5 }, { later: [{ p: 0.5, in: 2, e: { fin: -15, lid: -5 }, text: 'Zvěst se potvrdila: lupiči přepadli karavanu se zásobami.' }] }],
    ['Doprovod pro kupce', { fin: -10, sil: 5 }, { later: [{ p: 0.5, in: 2, e: { fin: 5 }, text: 'Kupci za bezpečné cesty platí ochotně a obchod kvete.' }] }],
    ['Nabídnout jim milost', { vir: 5, sil: -5 }, { later: [{ p: 0.5, in: 2, e: { sil: 5, lid: -5 }, text: 'Lupiči milost přijali a vstoupili do služeb, lidé se jich ale bojí.' }] }],
    rum),
  k('zvest_zazrak', '@rada', 'Posel tvrdí, že na hoře se zjevil zázrak, {osl}. Poutníci se tam už sbíhají ze všech stran.',
    ['Postavit tam svatyni', { fin: -10, vir: 10 }, { later: [{ p: 0.5, in: 3, e: { vir: -10, lid: -5 }, text: 'Zázrak se ukázal jako podvod. Svatyně stojí prázdná a lidé se smějí.' }] }],
    ['Je to podvod', { ved: 5, vir: -5 }, { later: [{ p: 0.5, in: 3, e: { vir: -10, lid: -10 }, text: 'Zázrak se opakoval před stovkami svědků. Lidé tvé pochybnosti nezapomenou.' }] }],
    ['Ať to učenci zkoumají', { ved: -5, vir: -5 }, { later: [{ p: 0.25, in: 3, e: { vir: -5 }, text: 'Učenci se s kněžími pohádali a spor rozdělil zemi.' }] }],
    ['Vybírat od poutníků', { fin: 10, vir: -5 }, { later: [{ p: 0.5, in: 3, e: { fin: -5, dip: -5 }, text: 'Poutníci přestali chodit a roznesli, že tu okrádáme věřící.' }] }],
    rum),
];

// ── Dlouhodobé ozvěny rozhodnutí ───────────────────────
const echo = { echo: true };
export const ECHO_CARDS = [
  k('ozvena_les', '@kraj', 'Na vypáleném svahu nic neroste, {osl}. Lidé navrhují vysadit les, ale ten bude užitečný až za mnoho let.',
    ['Vysadit les', { fin: -10, lid: -5 }, { later: [{ p: 1, in: 36, e: { pri: 15, fin: 10 }, text: 'Les, který jsi dal{a} před lety vysadit, dorostl. Dává dřevo, zvěř i čistou vodu.' }] }],
    ['Udělat z něj pastviny', { fin: 10, pri: -5 }, { later: [{ p: 1, in: 36, e: { pri: -15, fin: -5 }, text: 'Pastviny na svahu, které jsi kdysi založil{a}, se vyčerpaly a půdu odnesly deště.' }] }],
    ['Nechat ho být', { pri: 5 }],
    ['Zasvětit ho předkům', { vir: 5, fin: -5 }],
    echo),
  k('ozvena_pujcka', '@rada', 'Obchodníci z ciziny nabízejí velkou půjčku, {osl}. Za dva roky ji ale budeme muset vrátit i s úrokem.',
    ['Vzít půjčku', { fin: 15, dip: 5 }, { later: [{ p: 1, in: 24, e: { fin: -20, dip: -5 }, text: 'Přišel čas splatit půjčku, kterou jsi vzal{a} před dvěma lety. Úroky nás pořádně zabolely.' }] }],
    ['Odmítnout', { dip: -5, fin: -5 }],
    ['Půjčit si méně', { fin: 5 }, { later: [{ p: 1, in: 24, e: { fin: -5 }, text: 'Splatili jsme malou půjčku z doby před dvěma lety. Bolelo to jen trochu.' }] }],
    ['Splácet zbožím', { pri: -10, fin: 5, dip: 5 }],
    echo),
  k('ozvena_sirotci', '@kraj', 'Po posledních nepokojích zůstaly v zemi desítky sirotků, {osl}. Kdo se o ně postará?',
    ['Vychovat je na náš účet', { fin: -10, lid: 5 }, { later: [{ p: 1, in: 48, e: { lid: 10, sil: 10 }, text: 'Sirotci, které jsi kdysi přijal{a}, vyrostli ve věrné lidi. Stojí za tebou v dobrém i zlém.' }] }],
    ['Ať se postarají kněží', { vir: 5, fin: -5 }],
    ['Ať si poradí sami', { fin: 5, lid: -10 }, { later: [{ p: 1, in: 48, e: { sil: -10, lid: -5 }, text: 'Opuštěné děti z dávných let vyrostly v lupiče. Pamatují si, že jsi je nechal{a} na pospas.' }] }],
    ['Poslat je k sousedům', { dip: 5, lid: -5 }],
    echo),
  k('ozvena_skola', '@rada', 'Učenci prosí o zřízení školy pro děti z chudých rodin, {osl}. Stojí to hodně a výsledek nebude hned vidět.',
    ['Zřídit školu', { fin: -15, ved: 5 }, { later: [{ p: 1, in: 48, e: { ved: 15, fin: 5 }, text: 'Děti ze školy, kterou jsi kdysi založil{a}, jsou dnes mistry svých řemesel.' }] }],
    ['Učit jen vybrané', { fin: -5, lid: -5, ved: 5 }],
    ['Peníze raději na zbraně', { sil: 10, ved: -5 }, { later: [{ p: 1, in: 36, e: { ved: -10, lid: -5 }, text: 'Generace bez učení dorostla. Nikdo neumí opravit, co předkové postavili.' }] }],
    ['Ať učí kněží', { vir: 5, ved: -5 }],
    echo),
  k('ozvena_reka', '@kraj', 'Řemeslníci chtějí vypouštět odpad do řeky, {osl}. Ušetří tím spoustu práce a zásob.',
    ['Povolit to', { fin: 10, lid: 5 }, { later: [{ p: 1, in: 30, e: { pri: -15, lid: -10 }, text: 'Řeka, do které jsi před lety dovolil{a} vypouštět odpad, je mrtvá. Ryby zmizely a lidé stůňou.' }] }],
    ['Zakázat to', { fin: -5, lid: -5, pri: 5 }],
    ['Ať staví jímky', { fin: -10, pri: 5 }, { later: [{ p: 1, in: 30, e: { pri: 10 }, text: 'Jímky, které jsi kdysi nařídil{a}, ochránily řeku. Je čistá a plná ryb.' }] }],
    ['Ať to učenci vyřeší', { ved: 5, fin: -5 }],
    echo),
  k('ozvena_hrad', '@rada', 'Velitelé navrhují postavit na hranici mohutné opevnění, {osl}. Bude to trvat roky a pohltí mnoho zásob.',
    ['Stavět opevnění', { fin: -15, lid: -5 }, { later: [{ p: 1, in: 36, e: { sil: 15, dip: 5 }, text: 'Opevnění, které jsi dal{a} kdysi postavit, odradilo nepřátele. Sousedé nás berou vážně.' }] }],
    ['Stačí strážní věže', { fin: -5, sil: 5 }],
    ['Raději dobré vztahy', { dip: 10, sil: -5 }],
    ['Utratit to za slavnosti', { lid: 10, fin: -5 }, { later: [{ p: 1, in: 36, e: { sil: -10, dip: -5 }, text: 'Nepřátelé si pamatují, že sis kdysi vybral{a} slavnosti místo obrany. Hranice jsou děravé.' }] }],
    echo),
  k('ozvena_cizinci', '@kraj', 'U hranic stojí skupina vyhnanců z daleké země, {osl}. Prosí o přijetí a slibují, že budou tvrdě pracovat.',
    ['Přijmout je', { fin: -10, lid: -5, dip: 5 }, { later: [{ p: 1, in: 36, e: { ved: 10, fin: 10 }, text: 'Vyhnanci, které jsi před lety přijal{a}, přinesli nová řemesla. Jejich děti jsou už naši.' }] }],
    ['Odmítnout je', { lid: 5, dip: -5 }],
    ['Přijmout jen zdatné', { fin: 5, vir: -5 }],
    ['Prodat je jako sluhy', { fin: 10, vir: -10 }, { later: [{ p: 1, in: 36, e: { dip: -15, lid: -5 }, text: 'Zpráva, jak jsi kdysi naložil{a} s vyhnanci, se roznesla po světě. Nikdo nám už nevěří.' }] }],
    echo),
  k('ozvena_sliby', '@rada', 'Lid žádá, abys slíbil{a} snížení dávek na příští roky, {osl}. Takový slib se ale špatně odvolává.',
    ['Slíbit to', { lid: 15, vir: -5 }, { later: [{ p: 1, in: 24, e: { fin: -15, lid: -5 }, text: 'Slib nižších dávek, který jsi kdysi dal{a}, vyprázdnil sýpky. Lidé přesto chtějí víc.' }] }],
    ['Odmítnout', { lid: -10, fin: 5 }],
    ['Slíbit jen málo', { lid: 5, fin: -5 }],
    ['Spojit to s prací', { lid: 5, sil: -5 }, { later: [{ p: 1, in: 24, e: { fin: 10, pri: -5 }, text: 'Cesty a hráze, které lidé kdysi stavěli místo dávek, dnes nesou užitek.' }] }],
    echo),
];
